server:
  port: 8082

spring:
  application:
    name: masterdata-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_masterdata
    username: ats_user
    password: ats_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ats_user
    password: ats_password