server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_auth
    username: ats_user
    password: ats_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: levuthanhduong2004@gmail.com
    password: qkas gspe vvdj fcqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "thay-bang-chuoi-bi-mat-it-nhat-256-bit-doi-truoc-khi-deploy"
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
  otp:
    expiration-minutes: 10