server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_auth
    username: ats_user
    password: ats_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ats_user
    password: ats_password
app:
  jwt:
    secret: ${JWT_SECRET:thay-bang-chuoi-bi-mat-it-nhat-256-bit-truoc-khi-deploy-thuc-te}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
  otp:
    expiration-minutes: 10