-- Phase 0 makes Flyway authoritative. CREATE IF NOT EXISTS supports both an empty database and
-- installations whose legacy schema was previously created by Hibernate ddl-auto=update.
CREATE TABLE IF NOT EXISTS interview (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    job_posting_id BIGINT NOT NULL,
    department_id BIGINT,
    assigned_recruiter_id BIGINT,
    candidate_id BIGINT,
    candidate_user_id_snapshot BIGINT,
    candidate_name_snapshot VARCHAR(255) NOT NULL,
    scheduled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    format VARCHAR(255) NOT NULL,
    work_location_id BIGINT,
    meeting_link VARCHAR(255),
    note TEXT,
    status VARCHAR(255) NOT NULL,
    candidate_confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    hm_confirmed_at TIMESTAMP WITHOUT TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE interview ADD COLUMN IF NOT EXISTS candidate_user_id_snapshot BIGINT;
ALTER TABLE interview ADD COLUMN IF NOT EXISTS hm_confirmed_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE interview ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS interview_interviewer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    interviewer_name_snapshot VARCHAR(255) NOT NULL,
    CONSTRAINT fk_interview_interviewer_interview FOREIGN KEY (interview_id) REFERENCES interview(id)
);

CREATE TABLE IF NOT EXISTS interview_evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL,
    interviewer_id BIGINT NOT NULL,
    overall_recommendation VARCHAR(255),
    general_comment TEXT,
    salary_proposed NUMERIC(38,2),
    salary_note TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_interview_evaluation_interview FOREIGN KEY (interview_id) REFERENCES interview(id)
);

CREATE TABLE IF NOT EXISTS interview_evaluation_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL REFERENCES interview_evaluation(id),
    criteria_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    comment VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS interview_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    candidate_name_snapshot VARCHAR(255) NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    format VARCHAR(255) NOT NULL,
    work_location_id BIGINT,
    meeting_link VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    department_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    candidate_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    matched BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS salary_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    interview_id BIGINT,
    proposed_salary NUMERIC(15,2) NOT NULL,
    comment TEXT,
    proposed_by_id BIGINT NOT NULL,
    proposed_by_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(80) NOT NULL,
    aggregate_version BIGINT,
    routing_key VARCHAR(120) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(24) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_error TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_interview_outbox_relay ON outbox_event(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS ix_interview_application_id ON interview(application_id);
CREATE INDEX IF NOT EXISTS ix_interview_candidate_id ON interview(candidate_id);
CREATE INDEX IF NOT EXISTS idx_interview_department ON interview(department_id);
CREATE INDEX IF NOT EXISTS idx_interview_assigned_recruiter ON interview(assigned_recruiter_id);
CREATE INDEX IF NOT EXISTS ix_interview_interviewer_user_id ON interview_interviewer(interviewer_id);
