-- Phase 1 expand migration: canonical schedule aggregate, state-transition log and resource
-- reservation ledger. Additive only. The legacy `interview` table is left in place and keeps
-- serving reads until the Phase 7 contract migration removes it.

-- ---------------------------------------------------------------------------------------------
-- 1. Aggregate
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schedule_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    department_id BIGINT,
    job_posting_id BIGINT,
    job_requisition_id BIGINT,
    interview_round INTEGER NOT NULL,
    allocation_mode VARCHAR(32) NOT NULL,
    break_minutes INTEGER NOT NULL DEFAULT 0,
    zone_id VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    cancel_reason VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_group_allocation_mode
        CHECK (allocation_mode IN ('SAME_START', 'SEQUENTIAL')),
    CONSTRAINT ck_schedule_group_break_minutes CHECK (break_minutes >= 0),
    CONSTRAINT ck_schedule_group_round CHECK (interview_round >= 1),
    CONSTRAINT ck_schedule_group_status CHECK (status IN (
        'DRAFT', 'PENDING_HM', 'PARTIALLY_APPROVED', 'HM_CHANGE_REQUESTED', 'PENDING_CANDIDATE',
        'PARTIALLY_CONFIRMED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES schedule_group(id),
    application_id BIGINT NOT NULL,
    job_posting_id BIGINT NOT NULL,
    job_requisition_id BIGINT,
    interview_round INTEGER NOT NULL,
    scorecard_template_id BIGINT,
    candidate_id BIGINT NOT NULL,
    candidate_user_id_snapshot BIGINT,
    candidate_name_snapshot VARCHAR(255) NOT NULL,
    department_id BIGINT,
    assigned_recruiter_id BIGINT,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    zone_id VARCHAR(64) NOT NULL,
    format VARCHAR(16) NOT NULL,
    meeting_link VARCHAR(1000),
    meeting_link_source VARCHAR(32),
    external_calendar_event_id VARCHAR(255),
    work_location_id BIGINT,
    meeting_room_id BIGINT,
    internal_note TEXT,
    candidate_visible_note TEXT,
    status VARCHAR(40) NOT NULL,
    primary_hm_id BIGINT NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    superseded_by_item_id BIGINT,
    supersedes_item_id BIGINT,
    hm_confirmed_at TIMESTAMP WITH TIME ZONE,
    candidate_confirmed_at TIMESTAMP WITH TIME ZONE,
    actual_start_at TIMESTAMP WITH TIME ZONE,
    actual_end_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    cancel_reason VARCHAR(500),
    legacy_interview_id BIGINT,
    legacy_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_item_format CHECK (format IN ('ONLINE', 'OFFLINE')),
    CONSTRAINT ck_schedule_item_link_source
        CHECK (meeting_link_source IS NULL OR meeting_link_source IN ('MANUAL', 'GOOGLE_CALENDAR')),
    CONSTRAINT ck_schedule_item_duration CHECK (duration_minutes > 0),
    CONSTRAINT ck_schedule_item_range CHECK (end_at > start_at),
    CONSTRAINT ck_schedule_item_revision CHECK (revision >= 1),
    CONSTRAINT ck_schedule_item_round CHECK (interview_round >= 1),
    CONSTRAINT ck_schedule_item_status CHECK (status IN (
        'DRAFT', 'PENDING_HM', 'HM_CHANGE_REQUESTED', 'PENDING_CANDIDATE',
        'CANDIDATE_CHANGE_REQUESTED', 'CANDIDATE_DECLINED', 'CONFIRMED', 'IN_PROGRESS',
        'COMPLETED_PENDING_EVALUATION', 'EVALUATED', 'CANDIDATE_NO_SHOW', 'INTERVIEWER_NO_SHOW',
        'CANCELLED', 'SUPERSEDED')),
    -- An online interview must carry the link the candidate is told to join, and an offline one a
    -- place to go. Enforced here so no caller can publish an item nobody can attend. Rows carried
    -- over from the legacy table are exempt: incomplete history is a fact to report, not something
    -- to fabricate a venue for.
    CONSTRAINT ck_schedule_item_venue CHECK (
        legacy_interview_id IS NOT NULL
        OR status IN ('DRAFT', 'CANCELLED', 'SUPERSEDED')
        OR (format = 'ONLINE' AND meeting_link IS NOT NULL)
        OR (format = 'OFFLINE' AND (work_location_id IS NOT NULL OR meeting_room_id IS NOT NULL)))
);

CREATE TABLE IF NOT EXISTS schedule_item_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    department_id_snapshot BIGINT,
    participant_role VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_participant_role CHECK (participant_role IN ('PRIMARY_HM', 'PANEL_HM'))
);

CREATE TABLE IF NOT EXISTS schedule_item_confirmation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    revision INTEGER NOT NULL,
    party VARCHAR(32) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    reason VARCHAR(500),
    decided_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_confirmation_party CHECK (party IN ('HIRING_MANAGER', 'CANDIDATE')),
    CONSTRAINT ck_schedule_confirmation_decision
        CHECK (decision IN ('CONFIRMED', 'CHANGE_REQUESTED', 'DECLINED'))
);

CREATE TABLE IF NOT EXISTS schedule_item_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    revision INTEGER NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    zone_id VARCHAR(64) NOT NULL,
    format VARCHAR(16) NOT NULL,
    meeting_link VARCHAR(1000),
    work_location_id BIGINT,
    meeting_room_id BIGINT,
    primary_hm_id BIGINT NOT NULL,
    status_at_snapshot VARCHAR(40) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    superseded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ux_schedule_item_revision UNIQUE (item_id, revision)
);

CREATE TABLE IF NOT EXISTS schedule_transition_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(24) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    aggregate_version BIGINT,
    item_revision INTEGER,
    from_status VARCHAR(40) NOT NULL,
    to_status VARCHAR(40) NOT NULL,
    action VARCHAR(40) NOT NULL,
    actor_user_id BIGINT,
    actor_role VARCHAR(32),
    reason VARCHAR(500),
    admin_override BOOLEAN NOT NULL DEFAULT FALSE,
    correlation_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_transition_aggregate CHECK (aggregate_type IN ('ITEM', 'GROUP')),
    -- An override is a deviation from policy, so it may never be recorded without a reason.
    CONSTRAINT ck_schedule_transition_override_reason
        CHECK (admin_override = FALSE OR reason IS NOT NULL)
);

-- ---------------------------------------------------------------------------------------------
-- 2. Resource reservation ledger
-- ---------------------------------------------------------------------------------------------

-- Required for an exclusion constraint that mixes equality on scalars with range overlap.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS resource_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BIGINT NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(24) NOT NULL,
    schedule_item_id BIGINT NOT NULL,
    schedule_item_revision INTEGER NOT NULL,
    schedule_group_id BIGINT,
    released_at TIMESTAMP WITH TIME ZONE,
    release_reason VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_resource_reservation_type
        CHECK (resource_type IN ('HIRING_MANAGER', 'CANDIDATE', 'MEETING_ROOM')),
    CONSTRAINT ck_resource_reservation_status
        CHECK (status IN ('HELD', 'CONFIRMED', 'RELEASED')),
    CONSTRAINT ck_resource_reservation_range CHECK (end_at > start_at),
    CONSTRAINT ck_resource_reservation_released
        CHECK (status <> 'RELEASED' OR released_at IS NOT NULL)
);

-- The invariant that actually decides a race: no resource can be held twice for overlapping time.
-- Released rows drop out of the constraint but stay for audit.
ALTER TABLE resource_reservation
    DROP CONSTRAINT IF EXISTS ux_resource_reservation_no_overlap;
ALTER TABLE resource_reservation
    ADD CONSTRAINT ux_resource_reservation_no_overlap
    EXCLUDE USING gist (
        resource_type WITH =,
        resource_id WITH =,
        tstzrange(start_at, end_at, '[)') WITH &&
    ) WHERE (status <> 'RELEASED');

-- ---------------------------------------------------------------------------------------------
-- 3. Indexes and remaining invariants
-- ---------------------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS ix_schedule_item_group ON schedule_item(group_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_application ON schedule_item(application_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_candidate ON schedule_item(candidate_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_department ON schedule_item(department_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_primary_hm ON schedule_item(primary_hm_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_status_start ON schedule_item(status, start_at);
CREATE INDEX IF NOT EXISTS ix_schedule_item_participant_user
    ON schedule_item_participant(user_id);
CREATE INDEX IF NOT EXISTS ix_schedule_item_confirmation_item
    ON schedule_item_confirmation(item_id, revision);
CREATE INDEX IF NOT EXISTS ix_schedule_transition_log_aggregate
    ON schedule_transition_log(aggregate_type, aggregate_id, created_at);
CREATE INDEX IF NOT EXISTS ix_resource_reservation_item
    ON resource_reservation(schedule_item_id, schedule_item_revision);
CREATE INDEX IF NOT EXISTS ix_resource_reservation_group
    ON resource_reservation(schedule_group_id);

-- One live item per application and round, so a batch cannot double-book the same candidate for
-- the same stage of the pipeline.
CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_item_active_application_round
    ON schedule_item(application_id, interview_round)
    WHERE status NOT IN ('CANCELLED', 'SUPERSEDED', 'CANDIDATE_DECLINED');

-- Exactly one primary hiring manager per item.
CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_item_single_primary_hm
    ON schedule_item_participant(item_id)
    WHERE participant_role = 'PRIMARY_HM';

CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_item_participant_unique
    ON schedule_item_participant(item_id, user_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_item_legacy_interview
    ON schedule_item(legacy_interview_id)
    WHERE legacy_interview_id IS NOT NULL;

-- A group must contain at least one item. This cannot be a plain CHECK, because the group row is
-- necessarily inserted before its items. A deferred constraint trigger asks the question at commit
-- time instead, which is the only moment the answer is meaningful.
CREATE OR REPLACE FUNCTION schedule_group_has_items() RETURNS trigger AS $trigger$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schedule_item WHERE group_id = NEW.id) THEN
        RAISE EXCEPTION 'Schedule group % has no items', NEW.id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$trigger$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_schedule_group_has_items ON schedule_group;
CREATE CONSTRAINT TRIGGER trg_schedule_group_has_items
    AFTER INSERT ON schedule_group
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION schedule_group_has_items();

-- ---------------------------------------------------------------------------------------------
-- 4. Migration reporting
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schedule_migration_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    target_group_id BIGINT,
    target_item_id BIGINT,
    disposition VARCHAR(40) NOT NULL,
    legacy_status VARCHAR(40),
    mapped_status VARCHAR(40),
    note VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_schedule_migration_disposition CHECK (disposition IN (
        'MIGRATED', 'MIGRATED_NEEDS_REVIEW', 'UNMAPPED', 'ARCHIVE_ONLY',
        'RESERVATION_SKIPPED_CONFLICT'))
);

CREATE INDEX IF NOT EXISTS ix_schedule_migration_report_disposition
    ON schedule_migration_report(disposition);

CREATE TABLE IF NOT EXISTS schedule_migration_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_version VARCHAR(20) NOT NULL,
    metric VARCHAR(80) NOT NULL,
    value BIGINT NOT NULL,
    ran_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Marks the legacy proposal-slot rows as superseded by the schedule aggregate. Unmapped by the
-- entity on purpose: nothing in the service reads or writes it, it exists so the Phase 7 contract
-- step can tell archived rows from anything that somehow appeared afterwards.
ALTER TABLE interview_slot ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

-- ---------------------------------------------------------------------------------------------
-- 5. Backfill from the legacy `interview` table
--
-- Mapping rules. Nothing here invents evidence that does not exist in the source row:
--   * hm_confirmed_at is the only proof a hiring manager approved. A legacy CONFIRMED row without
--     it is migrated as PENDING_HM and flagged for review, never as an approved schedule.
--   * COMPLETED and CANCELLED are terminal facts and are honoured, but a completed interview with
--     no hiring-manager approval on record is still flagged, because the mandatory confirmation
--     chain cannot be reconstructed after the fact.
--   * A legacy interview with no interviewer has no possible primary hiring manager and is left
--     unmapped rather than assigned to an arbitrary person.
-- ---------------------------------------------------------------------------------------------

DO $migration$
DECLARE
    -- The legacy columns are wall-clock local times with no zone recorded. This is the company
    -- zone they were entered in; it is the single assumption of the backfill and is reported.
    default_zone CONSTANT TEXT := 'Asia/Ho_Chi_Minh';
    legacy RECORD;
    new_group_id BIGINT;
    new_item_id BIGINT;
    mapped_status TEXT;
    needs_review BOOLEAN;
    review_note TEXT;
    primary_hm BIGINT;
    interviewer_count INTEGER;
    pending_evaluations INTEGER;
    item_start TIMESTAMPTZ;
    item_end TIMESTAMPTZ;
    reserved_conflicts INTEGER := 0;
    row_failed BOOLEAN;
BEGIN
    IF to_regclass('public.interview') IS NULL THEN
        RETURN;
    END IF;

    FOR legacy IN
        SELECT i.*,
               -- Legacy rows carry no round. Successive interviews on the same application are
               -- numbered in date order, which is both the natural reading and what keeps the
               -- "one live item per application and round" index satisfiable.
               row_number() OVER (
                   PARTITION BY i.application_id ORDER BY i.scheduled_at, i.id) AS derived_round
          FROM interview i
         WHERE NOT EXISTS (SELECT 1 FROM schedule_item s WHERE s.legacy_interview_id = i.id)
         ORDER BY i.id
    LOOP
        needs_review := FALSE;
        review_note := NULL;
        row_failed := FALSE;

        SELECT count(*), min(interviewer_id)
          INTO interviewer_count, primary_hm
          FROM interview_interviewer WHERE interview_id = legacy.id;

        IF interviewer_count = 0 OR primary_hm IS NULL THEN
            INSERT INTO schedule_migration_report(
                source_table, source_id, disposition, legacy_status, note)
            VALUES ('interview', legacy.id, 'UNMAPPED', legacy.status::TEXT,
                    'No interviewer on the legacy row, so no primary hiring manager can be '
                    || 'derived. Assign a panel and re-run the backfill for this row.');
            CONTINUE;
        END IF;

        IF legacy.candidate_id IS NULL THEN
            INSERT INTO schedule_migration_report(
                source_table, source_id, disposition, legacy_status, note)
            VALUES ('interview', legacy.id, 'UNMAPPED', legacy.status::TEXT,
                    'No candidate id on the legacy row. Link the application to its candidate '
                    || 'and re-run the backfill for this row.');
            CONTINUE;
        END IF;

        IF legacy.duration_minutes IS NULL OR legacy.duration_minutes <= 0 THEN
            INSERT INTO schedule_migration_report(
                source_table, source_id, disposition, legacy_status, note)
            VALUES ('interview', legacy.id, 'UNMAPPED', legacy.status::TEXT,
                    'Legacy duration is not a positive number of minutes, so no time range can '
                    || 'be derived. Correct the source row and re-run the backfill.');
            CONTINUE;
        END IF;

        IF interviewer_count > 1 THEN
            needs_review := TRUE;
            review_note := 'Panel of ' || interviewer_count
                || ' with no designated primary hiring manager; lowest user id was used.';
        END IF;

        SELECT count(*) INTO pending_evaluations
          FROM interview_interviewer ii
          LEFT JOIN interview_evaluation e
            ON e.interview_id = ii.interview_id AND e.interviewer_id = ii.interviewer_id
         WHERE ii.interview_id = legacy.id
           AND (e.id IS NULL OR e.submitted_at IS NULL);

        IF legacy.status::TEXT = 'CANCELLED' THEN
            mapped_status := 'CANCELLED';
        ELSIF legacy.status::TEXT = 'COMPLETED' THEN
            mapped_status := CASE WHEN pending_evaluations = 0
                                  THEN 'EVALUATED' ELSE 'COMPLETED_PENDING_EVALUATION' END;
            IF legacy.hm_confirmed_at IS NULL THEN
                needs_review := TRUE;
                review_note := concat_ws(' ', review_note,
                    'Completed without a recorded hiring-manager confirmation.');
            END IF;
        ELSIF legacy.hm_confirmed_at IS NOT NULL AND legacy.candidate_confirmed_at IS NOT NULL THEN
            mapped_status := 'CONFIRMED';
        ELSIF legacy.hm_confirmed_at IS NOT NULL THEN
            mapped_status := 'PENDING_CANDIDATE';
        ELSE
            -- No proof of the mandatory hiring-manager approval: the item goes back to the gate.
            mapped_status := 'PENDING_HM';
            IF legacy.status::TEXT = 'CONFIRMED' OR legacy.candidate_confirmed_at IS NOT NULL THEN
                needs_review := TRUE;
                review_note := concat_ws(' ', review_note,
                    'Legacy row looked confirmed but carries no hiring-manager confirmation; '
                    || 'the candidate confirmation was kept as history and the item returns to '
                    || 'the hiring-manager gate.');
            END IF;
        END IF;

        item_start := legacy.scheduled_at AT TIME ZONE default_zone;
        item_end := item_start + make_interval(mins => legacy.duration_minutes);

        -- The aggregate is written in a sub-transaction. If a database invariant rejects a legacy
        -- row, that single row is reported as unmapped instead of aborting the whole migration.
        BEGIN
            INSERT INTO schedule_group(
                title, department_id, job_posting_id, interview_round, allocation_mode,
                break_minutes, zone_id, status, created_by_user_id, version, created_at, updated_at)
            VALUES (
                'Lịch phỏng vấn ' || legacy.candidate_name_snapshot || ' - '
                    || to_char(legacy.scheduled_at, 'DD/MM/YYYY'),
                legacy.department_id, legacy.job_posting_id, legacy.derived_round::INTEGER,
                'SAME_START', 0, default_zone, 'DRAFT',
                COALESCE(legacy.assigned_recruiter_id, primary_hm),
                0, COALESCE(legacy.created_at AT TIME ZONE default_zone, now()), now())
            RETURNING id INTO new_group_id;

            INSERT INTO schedule_item(
                group_id, application_id, job_posting_id, interview_round, candidate_id,
                candidate_user_id_snapshot, candidate_name_snapshot, department_id,
                assigned_recruiter_id, start_at, end_at, duration_minutes, zone_id, format,
                meeting_link, meeting_link_source, work_location_id, internal_note, status,
                primary_hm_id, revision, hm_confirmed_at, candidate_confirmed_at, cancelled_at,
                legacy_interview_id, legacy_review_required, version, created_at, updated_at)
            VALUES (
                new_group_id, legacy.application_id, legacy.job_posting_id,
                legacy.derived_round::INTEGER, legacy.candidate_id,
                legacy.candidate_user_id_snapshot, legacy.candidate_name_snapshot,
                legacy.department_id, legacy.assigned_recruiter_id,
                item_start, item_end, legacy.duration_minutes, default_zone, legacy.format::TEXT,
                legacy.meeting_link,
                CASE WHEN legacy.meeting_link IS NULL THEN NULL ELSE 'MANUAL' END,
                legacy.work_location_id, legacy.note, mapped_status, primary_hm, 1,
                legacy.hm_confirmed_at AT TIME ZONE default_zone,
                legacy.candidate_confirmed_at AT TIME ZONE default_zone,
                CASE WHEN mapped_status = 'CANCELLED' THEN now() ELSE NULL END,
                legacy.id, needs_review, 0,
                COALESCE(legacy.created_at AT TIME ZONE default_zone, now()), now())
            RETURNING id INTO new_item_id;

            INSERT INTO schedule_item_participant(
                item_id, user_id, name_snapshot, participant_role, created_at)
            SELECT new_item_id, ii.interviewer_id, ii.interviewer_name_snapshot,
                   CASE WHEN ii.interviewer_id = primary_hm THEN 'PRIMARY_HM' ELSE 'PANEL_HM' END,
                   now()
              FROM interview_interviewer ii
             WHERE ii.interview_id = legacy.id;

            -- Keep the confirmations that really happened, attributed to the party that made them.
            IF legacy.hm_confirmed_at IS NOT NULL THEN
                INSERT INTO schedule_item_confirmation(
                    item_id, revision, party, decision, actor_user_id, reason, decided_at)
                VALUES (new_item_id, 1, 'HIRING_MANAGER', 'CONFIRMED', primary_hm,
                        'Migrated from legacy interview row',
                        legacy.hm_confirmed_at AT TIME ZONE default_zone);
            END IF;
            IF legacy.candidate_confirmed_at IS NOT NULL
                   AND legacy.candidate_user_id_snapshot IS NOT NULL THEN
                INSERT INTO schedule_item_confirmation(
                    item_id, revision, party, decision, actor_user_id, reason, decided_at)
                VALUES (new_item_id, 1, 'CANDIDATE', 'CONFIRMED',
                        legacy.candidate_user_id_snapshot,
                        'Migrated from legacy interview row',
                        legacy.candidate_confirmed_at AT TIME ZONE default_zone);
            END IF;

            INSERT INTO schedule_item_revision(
                item_id, revision, start_at, end_at, zone_id, format, meeting_link,
                work_location_id, primary_hm_id, status_at_snapshot, created_by_user_id, reason,
                created_at)
            VALUES (new_item_id, 1, item_start, item_end, default_zone, legacy.format::TEXT,
                    legacy.meeting_link, legacy.work_location_id, primary_hm, mapped_status,
                    COALESCE(legacy.assigned_recruiter_id, primary_hm),
                    'Phase 1 backfill from legacy interview row', now());

            INSERT INTO schedule_transition_log(
                aggregate_type, aggregate_id, aggregate_version, item_revision, from_status,
                to_status, action, actor_user_id, actor_role, reason, admin_override, created_at)
            VALUES ('ITEM', new_item_id, 0, 1, 'DRAFT', mapped_status, 'MIGRATE', NULL, 'SYSTEM',
                    'Phase 1 backfill from legacy interview ' || legacy.id, FALSE, now());
        EXCEPTION WHEN unique_violation OR check_violation OR foreign_key_violation
                    OR not_null_violation THEN
            row_failed := TRUE;
            INSERT INTO schedule_migration_report(
                source_table, source_id, disposition, legacy_status, mapped_status, note)
            VALUES ('interview', legacy.id, 'UNMAPPED', legacy.status::TEXT, mapped_status,
                    -- SQLERRM has no length bound; overflowing note here would abort the whole
                    -- migration from inside the handler meant to keep it going.
                    left('Rejected by a schedule invariant: ' || SQLERRM, 500));
        END;

        IF row_failed THEN
            CONTINUE;
        END IF;

        -- Live items must hold their resources, or the new pre-check would happily double-book on
        -- top of a legacy schedule. Legacy data allowed overlaps, so a clash is recorded for HR
        -- instead of aborting the whole migration.
        IF mapped_status NOT IN ('CANCELLED', 'EVALUATED', 'COMPLETED_PENDING_EVALUATION') THEN
            BEGIN
                INSERT INTO resource_reservation(
                    resource_type, resource_id, start_at, end_at, status, schedule_item_id,
                    schedule_item_revision, schedule_group_id, version, created_at, updated_at)
                SELECT 'HIRING_MANAGER', ii.interviewer_id, item_start, item_end, 'HELD',
                       new_item_id, 1, new_group_id, 0, now(), now()
                  FROM interview_interviewer ii WHERE ii.interview_id = legacy.id;

                IF legacy.candidate_id IS NOT NULL THEN
                    INSERT INTO resource_reservation(
                        resource_type, resource_id, start_at, end_at, status, schedule_item_id,
                        schedule_item_revision, schedule_group_id, version, created_at, updated_at)
                    VALUES ('CANDIDATE', legacy.candidate_id, item_start, item_end, 'HELD',
                            new_item_id, 1, new_group_id, 0, now(), now());
                END IF;
            EXCEPTION WHEN exclusion_violation THEN
                reserved_conflicts := reserved_conflicts + 1;
                needs_review := TRUE;
                UPDATE schedule_item SET legacy_review_required = TRUE WHERE id = new_item_id;
                INSERT INTO schedule_migration_report(
                    source_table, source_id, target_group_id, target_item_id, disposition,
                    legacy_status, mapped_status, note)
                VALUES ('interview', legacy.id, new_group_id, new_item_id,
                        'RESERVATION_SKIPPED_CONFLICT', legacy.status::TEXT, mapped_status,
                        'The legacy schedule overlaps another booking for the same hiring manager '
                        || 'or candidate. No reservation was created; HR must reschedule one of '
                        || 'the two before this item can be confirmed.');
            END;
        END IF;

        UPDATE schedule_group
           SET status = CASE mapped_status
                            WHEN 'CANCELLED' THEN 'CANCELLED'
                            WHEN 'EVALUATED' THEN 'COMPLETED'
                            WHEN 'COMPLETED_PENDING_EVALUATION' THEN 'IN_PROGRESS'
                            WHEN 'CONFIRMED' THEN 'CONFIRMED'
                            WHEN 'PENDING_CANDIDATE' THEN 'PENDING_CANDIDATE'
                            ELSE 'PENDING_HM'
                        END
         WHERE id = new_group_id;

        INSERT INTO schedule_migration_report(
            source_table, source_id, target_group_id, target_item_id, disposition, legacy_status,
            mapped_status, note)
        VALUES ('interview', legacy.id, new_group_id, new_item_id,
                CASE WHEN needs_review THEN 'MIGRATED_NEEDS_REVIEW' ELSE 'MIGRATED' END,
                legacy.status::TEXT, mapped_status, review_note);
    END LOOP;

    -- Legacy proposal slots are not schedules: a PROPOSED slot was never a commitment, and a
    -- matched one already produced an interview row that the loop above migrated. They are
    -- recorded and archived, not converted. Writes to this table are already disabled by the
    -- Phase 0 feature flag; the stamp marks the rows as superseded by the schedule aggregate so
    -- the table can be dropped in the Phase 7 contract step.
    IF to_regclass('public.interview_slot') IS NOT NULL THEN
        INSERT INTO schedule_migration_report(
            source_table, source_id, disposition, legacy_status, note)
        SELECT 'interview_slot', s.id, 'ARCHIVE_ONLY', s.status::TEXT,
               CASE WHEN s.matched
                    THEN 'Matched slot; the interview it produced was migrated separately.'
                    ELSE 'Unmatched proposal slot; never a committed schedule.' END
          FROM interview_slot s
         WHERE NOT EXISTS (
             SELECT 1 FROM schedule_migration_report r
              WHERE r.source_table = 'interview_slot' AND r.source_id = s.id);

        UPDATE interview_slot SET archived_at = now() WHERE archived_at IS NULL;
    END IF;

    INSERT INTO schedule_migration_summary(migration_version, metric, value)
    VALUES ('V5', 'legacy_interview_rows',
            (SELECT count(*) FROM interview)),
           ('V5', 'schedule_items_created',
            (SELECT count(*) FROM schedule_item WHERE legacy_interview_id IS NOT NULL)),
           ('V5', 'items_needing_review',
            (SELECT count(*) FROM schedule_item WHERE legacy_review_required)),
           ('V5', 'rows_unmapped',
            (SELECT count(*) FROM schedule_migration_report WHERE disposition = 'UNMAPPED')),
           ('V5', 'reservation_conflicts', reserved_conflicts),
           ('V5', 'reservations_created',
            (SELECT count(*) FROM resource_reservation));
END
$migration$;
