-- Phase 4: what happened during the interview, and what was concluded from it.
--
-- Additive. Nothing here rewrites a Phase 1-3 row, and the legacy `interview_evaluation` tables
-- are left untouched: they belong to the old `interview` aggregate and are removed by the Phase 7
-- contract migration, not by this one.

-- ---------------------------------------------------------------------------------------------
-- 1. What went wrong during the hour
-- ---------------------------------------------------------------------------------------------

-- Separate from schedule_transition_log, and the two answer different questions. The transition
-- log is an audit of the state machine: how did this schedule reach the status it is in. This is
-- the record of the session itself, and most of what belongs in it changes no status at all -- a
-- candidate who arrived twenty minutes late still had their interview.
CREATE TABLE IF NOT EXISTS schedule_item_exception (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    item_revision INTEGER NOT NULL,
    type VARCHAR(40) NOT NULL,
    -- Mandatory. "Did not attend" and "did not attend, called an hour later to say they had the
    -- wrong link" are different claims about the same person, and only one of them is fair.
    note VARCHAR(1000) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_role VARCHAR(32),
    subject_user_id BIGINT,
    waited_minutes INTEGER,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_exception_type CHECK (type IN (
        'CANDIDATE_LATE', 'INTERVIEWER_LATE', 'CANDIDATE_NO_SHOW',
        'INTERVIEWER_NO_SHOW', 'NEXT_SESSIONS_DELAYED')),
    CONSTRAINT ck_schedule_exception_waited CHECK (waited_minutes IS NULL OR waited_minutes >= 0)
);

CREATE INDEX IF NOT EXISTS ix_schedule_item_exception_item
    ON schedule_item_exception(item_id, occurred_at);

-- ---------------------------------------------------------------------------------------------
-- 2. The scorecard, frozen per interview
-- ---------------------------------------------------------------------------------------------

-- A copy of master data rather than a reference to it, which is the whole point. Criteria get
-- renamed, weights get rebalanced, some are retired. Without this, reopening a scorecard from
-- three months ago would show scores against criteria that have since changed meaning, and two
-- candidates interviewed either side of an edit would be compared on numbers that were never on
-- the same scale.
CREATE TABLE IF NOT EXISTS schedule_scorecard_criterion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    criteria_id BIGINT NOT NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    description_snapshot TEXT,
    weight NUMERIC(5,2) NOT NULL,
    max_score INTEGER NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_scorecard_criterion_weight CHECK (weight >= 0),
    CONSTRAINT ck_scorecard_criterion_max_score CHECK (max_score >= 1)
);

-- One row per criterion per interview: the snapshot is taken once and is not a growing list.
CREATE UNIQUE INDEX IF NOT EXISTS ux_scorecard_criterion_item_criteria
    ON schedule_scorecard_criterion(item_id, criteria_id);

-- ---------------------------------------------------------------------------------------------
-- 3. One scorecard per hiring manager
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schedule_evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    item_revision INTEGER NOT NULL,
    hiring_manager_id BIGINT NOT NULL,
    hiring_manager_name_snapshot VARCHAR(255) NOT NULL,
    status VARCHAR(24) NOT NULL,
    overall_recommendation VARCHAR(24),
    general_comment TEXT,
    strengths TEXT,
    weaknesses TEXT,
    risks TEXT,
    salary_proposed NUMERIC(15,2),
    salary_currency VARCHAR(8),
    salary_note TEXT,
    -- Computed once at submission, from the weights that were snapshotted. Recomputing on read
    -- would give a different answer as soon as master data moved on.
    weighted_score NUMERIC(10,4),
    max_weighted_score NUMERIC(10,4),
    submitted_at TIMESTAMP WITH TIME ZONE,
    reopened_at TIMESTAMP WITH TIME ZONE,
    reopened_by_user_id BIGINT,
    reopen_reason VARCHAR(500),
    reopen_count INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_schedule_evaluation_status CHECK (status IN ('DRAFT', 'SUBMITTED')),
    CONSTRAINT ck_schedule_evaluation_recommendation CHECK (
        overall_recommendation IS NULL
        OR overall_recommendation IN ('STRONG_YES', 'YES', 'NO', 'STRONG_NO')),
    -- A submitted scorecard has to carry the two things a decision is taken on.
    CONSTRAINT ck_schedule_evaluation_submitted CHECK (
        status <> 'SUBMITTED'
        OR (submitted_at IS NOT NULL AND overall_recommendation IS NOT NULL)),
    CONSTRAINT ck_schedule_evaluation_reopen CHECK (
        reopen_count = 0 OR (reopened_at IS NOT NULL AND reopen_reason IS NOT NULL)),
    CONSTRAINT ck_schedule_evaluation_salary CHECK (
        salary_proposed IS NULL OR salary_proposed >= 0)
);

-- One assessment per person per interview. Three people who sat in the same hour saw different
-- things; merging them would lose the disagreement that makes a panel worth having.
CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_evaluation_item_hm
    ON schedule_evaluation(item_id, hiring_manager_id);

CREATE INDEX IF NOT EXISTS ix_schedule_evaluation_item_status
    ON schedule_evaluation(item_id, status);

CREATE TABLE IF NOT EXISTS schedule_evaluation_score (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL REFERENCES schedule_evaluation(id) ON DELETE CASCADE,
    criteria_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    comment TEXT,
    CONSTRAINT ck_schedule_evaluation_score_range CHECK (score >= 0)
);

-- The upper bound is not here: it belongs to the criterion, which carries its own scale in the
-- snapshot, and is checked against that rather than against a number frozen into a constraint.
CREATE UNIQUE INDEX IF NOT EXISTS ux_schedule_evaluation_score_criteria
    ON schedule_evaluation_score(evaluation_id, criteria_id);

-- ---------------------------------------------------------------------------------------------
-- 4. The primary hiring manager's conclusion
-- ---------------------------------------------------------------------------------------------

-- Separate from the scorecards, because a scorecard is one person's observation and a decision is
-- one person's accountability. It also lets the decision name a panel it disagrees with.
--
-- Nothing in the service derives a row here from an average, and nothing here moves an
-- application: how many people can actually be hired depends on the headcount left and on who
-- else was interviewed, which is the selection round's question in Phase 5.
CREATE TABLE IF NOT EXISTS schedule_final_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL UNIQUE REFERENCES schedule_item(id) ON DELETE CASCADE,
    item_revision INTEGER NOT NULL,
    decided_by_user_id BIGINT NOT NULL,
    decided_by_name_snapshot VARCHAR(255) NOT NULL,
    recommendation VARCHAR(32) NOT NULL,
    reason TEXT NOT NULL,
    -- Where the panel leaned at the moment of the decision, stored rather than recomputed: reading
    -- a decision against evidence that has since changed is how a reasonable call comes to look
    -- arbitrary.
    panel_consensus VARCHAR(16) NOT NULL,
    overrides_panel BOOLEAN NOT NULL DEFAULT FALSE,
    override_reason TEXT,
    average_weighted_score NUMERIC(10,4),
    missing_evaluations INTEGER NOT NULL DEFAULT 0,
    decided_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_final_decision_recommendation CHECK (recommendation IN (
        'SELECTED_FOR_OFFER', 'NEXT_INTERVIEW', 'WAITLIST', 'HOLD', 'REJECTED')),
    CONSTRAINT ck_final_decision_consensus CHECK (
        panel_consensus IN ('POSITIVE', 'NEGATIVE', 'MIXED')),
    -- Going against the panel is allowed; doing so silently is not.
    CONSTRAINT ck_final_decision_override_reason CHECK (
        overrides_panel = FALSE OR override_reason IS NOT NULL),
    CONSTRAINT ck_final_decision_missing CHECK (missing_evaluations >= 0)
);

CREATE INDEX IF NOT EXISTS ix_final_decision_recommendation
    ON schedule_final_decision(recommendation, decided_at);

-- ---------------------------------------------------------------------------------------------
-- 5. The scheduler's index
-- ---------------------------------------------------------------------------------------------

-- The time-driven scan runs every thirty seconds and asks exactly two questions: which confirmed
-- interviews have started, and which running ones have finished. ix_schedule_item_status_start
-- from V5 already covers the first; this covers the second.
CREATE INDEX IF NOT EXISTS ix_schedule_item_status_end
    ON schedule_item(status, end_at);
