-- Phase 5: compare evaluated candidates and make one quota-bound, human decision per candidate.

CREATE TABLE IF NOT EXISTS selection_round (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_requisition_id BIGINT NOT NULL,
    interview_round INTEGER NOT NULL,
    department_id BIGINT NOT NULL,
    scorecard_fingerprint VARCHAR(64) NOT NULL,
    primary_hm_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    target_snapshot INTEGER NOT NULL,
    reserved_snapshot INTEGER NOT NULL,
    filled_snapshot INTEGER NOT NULL,
    remaining_snapshot INTEGER NOT NULL,
    finalize_command_id UUID UNIQUE,
    finalize_expected_version BIGINT,
    finalized_by_user_id BIGINT,
    finalized_at TIMESTAMP WITH TIME ZONE,
    admin_override BOOLEAN NOT NULL DEFAULT FALSE,
    admin_override_reason TEXT,
    headcount_lease_until TIMESTAMP WITH TIME ZONE,
    headcount_confirmed_at TIMESTAMP WITH TIME ZONE,
    headcount_confirmation_error TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_selection_round_number CHECK (interview_round >= 1),
    CONSTRAINT ck_selection_round_status CHECK (status IN ('DRAFT', 'FINALIZED')),
    CONSTRAINT ck_selection_round_headcount CHECK (
        target_snapshot >= 0 AND reserved_snapshot >= 0 AND filled_snapshot >= 0
        AND remaining_snapshot >= 0),
    CONSTRAINT ck_selection_round_finalized CHECK (
        (status = 'DRAFT' AND finalized_at IS NULL AND finalized_by_user_id IS NULL
            AND finalize_command_id IS NULL AND finalize_expected_version IS NULL)
        OR
        (status = 'FINALIZED' AND finalized_at IS NOT NULL AND finalized_by_user_id IS NOT NULL
            AND finalize_command_id IS NOT NULL AND finalize_expected_version IS NOT NULL)),
    CONSTRAINT ck_selection_round_override CHECK (
        admin_override = FALSE OR admin_override_reason IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_selection_round_scope
    ON selection_round(job_requisition_id, interview_round, status);
CREATE INDEX IF NOT EXISTS ix_selection_round_primary_hm
    ON selection_round(primary_hm_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_selection_round_headcount_reconcile
    ON selection_round(status, headcount_confirmed_at, created_at)
    WHERE status = 'FINALIZED' AND headcount_confirmed_at IS NULL;

CREATE TABLE IF NOT EXISTS selection_round_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES selection_round(id) ON DELETE CASCADE,
    schedule_item_id BIGINT NOT NULL REFERENCES schedule_item(id),
    item_revision INTEGER NOT NULL,
    application_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    candidate_user_id BIGINT,
    candidate_name_snapshot VARCHAR(255) NOT NULL,
    status_snapshot VARCHAR(40) NOT NULL,
    recommendation_snapshot VARCHAR(32) NOT NULL,
    panel_comments_snapshot TEXT,
    experience_snapshot TEXT,
    skills_snapshot TEXT,
    salary_proposed NUMERIC(15,2),
    salary_currency VARCHAR(8),
    available_start_date DATE,
    average_weighted_score NUMERIC(10,4),
    max_weighted_score NUMERIC(10,4),
    normalized_score NUMERIC(7,4),
    decision VARCHAR(32),
    decision_reason TEXT,
    decided_by_user_id BIGINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ux_selection_candidate_item UNIQUE(round_id, schedule_item_id),
    CONSTRAINT ux_selection_candidate_schedule_item UNIQUE(schedule_item_id),
    CONSTRAINT ux_selection_candidate_application UNIQUE(round_id, application_id),
    CONSTRAINT ck_selection_candidate_recommendation CHECK (recommendation_snapshot IN (
        'SELECTED_FOR_OFFER', 'NEXT_INTERVIEW', 'WAITLIST', 'HOLD', 'REJECTED')),
    CONSTRAINT ck_selection_candidate_decision CHECK (decision IS NULL OR decision IN (
        'SELECTED_FOR_OFFER', 'WAITLIST', 'HOLD', 'REJECTED')),
    CONSTRAINT ck_selection_candidate_decision_evidence CHECK (
        (decision IS NULL AND decision_reason IS NULL AND decided_by_user_id IS NULL AND decided_at IS NULL)
        OR
        (decision IS NOT NULL AND decision_reason IS NOT NULL
            AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT ck_selection_candidate_score CHECK (
        normalized_score IS NULL OR (normalized_score >= 0 AND normalized_score <= 100)),
    CONSTRAINT ck_selection_candidate_salary CHECK (salary_proposed IS NULL OR salary_proposed >= 0)
);

CREATE INDEX IF NOT EXISTS ix_selection_candidate_round ON selection_round_candidate(round_id);
CREATE INDEX IF NOT EXISTS ix_selection_candidate_application ON selection_round_candidate(application_id);
CREATE INDEX IF NOT EXISTS ix_selection_candidate_decision ON selection_round_candidate(decision);

CREATE TABLE IF NOT EXISTS selection_candidate_criterion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    selection_candidate_id BIGINT NOT NULL
        REFERENCES selection_round_candidate(id) ON DELETE CASCADE,
    criteria_id BIGINT NOT NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    weight NUMERIC(5,2) NOT NULL,
    max_score INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    average_score NUMERIC(10,4),
    comments_snapshot TEXT,
    CONSTRAINT ux_selection_candidate_criterion UNIQUE(selection_candidate_id, criteria_id),
    CONSTRAINT ck_selection_criterion_weight CHECK (weight >= 0),
    CONSTRAINT ck_selection_criterion_max CHECK (max_score >= 1),
    CONSTRAINT ck_selection_criterion_average CHECK (
        average_score IS NULL OR (average_score >= 0 AND average_score <= max_score))
);

CREATE TABLE IF NOT EXISTS selection_round_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES selection_round(id),
    aggregate_version BIGINT,
    action VARCHAR(40) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_role VARCHAR(32) NOT NULL,
    reason TEXT,
    admin_override BOOLEAN NOT NULL DEFAULT FALSE,
    correlation_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_selection_audit_override CHECK (
        admin_override = FALSE OR reason IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_selection_audit_round
    ON selection_round_audit(round_id, created_at);

-- An audit trail is evidence, not mutable application state.
CREATE OR REPLACE FUNCTION selection_audit_is_append_only() RETURNS trigger AS $body$
BEGIN
    RAISE EXCEPTION 'selection_round_audit is append-only'
        USING ERRCODE = 'restrict_violation';
END;
$body$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_selection_audit_append_only ON selection_round_audit;
CREATE TRIGGER trg_selection_audit_append_only
    BEFORE UPDATE OR DELETE ON selection_round_audit
    FOR EACH ROW EXECUTE FUNCTION selection_audit_is_append_only();

CREATE TABLE IF NOT EXISTS selection_workflow_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES selection_round(id),
    selection_candidate_id BIGINT NOT NULL REFERENCES selection_round_candidate(id),
    task_type VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    assigned_recruiter_id BIGINT,
    completed_by_user_id BIGINT,
    completion_note TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_selection_task_once UNIQUE(selection_candidate_id, task_type),
    CONSTRAINT ck_selection_task_type CHECK (task_type IN ('PREPARE_OFFER', 'REVIEW_REJECTION')),
    CONSTRAINT ck_selection_task_status CHECK (status IN ('OPEN', 'COMPLETED')),
    CONSTRAINT ck_selection_task_completed CHECK (
        (status = 'OPEN' AND completed_at IS NULL AND completed_by_user_id IS NULL)
        OR (status = 'COMPLETED' AND completed_at IS NOT NULL AND completed_by_user_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS ix_selection_task_inbox
    ON selection_workflow_task(status, assigned_recruiter_id, created_at DESC);
