server:
  port: 8084

spring:
  application:
    name: candidate-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_candidate
    username: ats_user
    password: ats_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ats_user
    password: ats_password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

services:
  auth-service:
    url: http://localhost:8081
  masterdata-service:
    url: http://localhost:8082
  recruitment-service:
    url: http://localhost:8083

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:}
    region: ${AWS_S3_REGION:ap-southeast-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:}0='
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}