CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    resource_type VARCHAR(255),
    resource_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255),
    resource_id BIGINT,
    metadata TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS processed_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_name VARCHAR(120) NOT NULL,
    event_id UUID NOT NULL,
    aggregate_version BIGINT,
    processed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_notification_inbox_consumer_event UNIQUE (consumer_name, event_id)
);

CREATE INDEX IF NOT EXISTS ix_notification_recipient_created
    ON notification(recipient_user_id, created_at DESC);
