server:
  port: 8083

spring:
  application:
    name: recruitment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_recruitment
    username: ats_user
    password: ats_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ats_user
    password: ats_password

services:
  auth-service:
    url: http://localhost:8081
  masterdata-service:
    url: http://localhost:8082