CREATE TABLE IF NOT EXISTS offer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    department_id BIGINT,
    assigned_recruiter_id BIGINT,
    candidate_id BIGINT,
    candidate_name_snapshot VARCHAR(255),
    salary_offered NUMERIC(38,2) NOT NULL,
    contract_type_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    probation_months INTEGER,
    response_deadline TIMESTAMP WITHOUT TIME ZONE,
    benefits TEXT,
    allowance NUMERIC(38,2),
    note TEXT,
    candidate_visible_note TEXT,
    requester_id BIGINT NOT NULL,
    approver_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    reject_reason VARCHAR(255),
    decline_reason_id BIGINT,
    decline_note VARCHAR(255),
    issued_at TIMESTAMP WITHOUT TIME ZONE,
    candidate_responded_at TIMESTAMP WITHOUT TIME ZONE,
    candidate_response_idempotency_key VARCHAR(120),
    candidate_response_action VARCHAR(16),
    version BIGINT NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE offer ADD COLUMN IF NOT EXISTS candidate_visible_note TEXT;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS candidate_responded_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS candidate_response_idempotency_key VARCHAR(120);
ALTER TABLE offer ADD COLUMN IF NOT EXISTS candidate_response_action VARCHAR(16);
ALTER TABLE offer ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS outbox_event (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(80) NOT NULL,
    aggregate_version BIGINT,
    routing_key VARCHAR(120) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(24) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_error TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_offer_outbox_relay ON outbox_event(status, available_at, created_at);
CREATE INDEX IF NOT EXISTS ix_offer_application_id ON offer(application_id);
CREATE INDEX IF NOT EXISTS ix_offer_candidate_id ON offer(candidate_id);
CREATE INDEX IF NOT EXISTS idx_offer_department_active ON offer(department_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_offer_assigned_recruiter_active ON offer(assigned_recruiter_id) WHERE deleted_at IS NULL;
