-- Phase 1 expand migration: offer case, version chain, sealed-version immutability and the
-- transition log. Additive only; no existing offer row changes status here.

-- ---------------------------------------------------------------------------------------------
-- 1. Case aggregate and version chain
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS offer_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    department_id BIGINT,
    assigned_recruiter_id BIGINT,
    candidate_id BIGINT,
    candidate_name_snapshot VARCHAR(255),
    job_requisition_id BIGINT,
    selection_decision_id BIGINT,
    status VARCHAR(32) NOT NULL,
    current_offer_id BIGINT,
    version_counter INTEGER NOT NULL DEFAULT 0,
    closed_at TIMESTAMP WITH TIME ZONE,
    legacy_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_offer_case_status CHECK (status IN (
        'OPEN', 'CLOSED_ACCEPTED', 'CLOSED_DECLINED', 'CLOSED_EXPIRED', 'CLOSED_WITHDRAWN',
        'CLOSED_CANCELLED')),
    CONSTRAINT ck_offer_case_version_counter CHECK (version_counter >= 0),
    CONSTRAINT ck_offer_case_closed CHECK (status = 'OPEN' OR closed_at IS NOT NULL)
);

-- An application may only have one open negotiation at a time.
--
-- Rows flagged legacy_review_required are excluded. Some historical applications carry two live
-- offers, which the new model has no honest representation for. Closing one of them would invent a
-- decision nobody made, so those rows are quarantined behind the flag and listed in
-- offer_migration_report. The invariant is fully enforced for everything written from here on, and
-- the flag is cleared as HR resolves each case.
CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_case_open_application
    ON offer_case(application_id)
    WHERE status = 'OPEN' AND legacy_review_required = FALSE;

CREATE INDEX IF NOT EXISTS ix_offer_case_application ON offer_case(application_id);
CREATE INDEX IF NOT EXISTS ix_offer_case_candidate ON offer_case(candidate_id);

ALTER TABLE offer ADD COLUMN IF NOT EXISTS offer_case_id BIGINT;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS version_no INTEGER NOT NULL DEFAULT 1;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS replaces_offer_version_id BIGINT;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS needs_revision_reason VARCHAR(500);
ALTER TABLE offer ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS sealed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS expired_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS withdrawn_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS withdraw_reason VARCHAR(500);
ALTER TABLE offer ADD COLUMN IF NOT EXISTS deadline_extension_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE offer ADD COLUMN IF NOT EXISTS legacy_review_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE offer DROP CONSTRAINT IF EXISTS fk_offer_case;
ALTER TABLE offer ADD CONSTRAINT fk_offer_case
    FOREIGN KEY (offer_case_id) REFERENCES offer_case(id);

ALTER TABLE offer DROP CONSTRAINT IF EXISTS fk_offer_replaces_version;
ALTER TABLE offer ADD CONSTRAINT fk_offer_replaces_version
    FOREIGN KEY (replaces_offer_version_id) REFERENCES offer(id);

ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_status;
ALTER TABLE offer ADD CONSTRAINT ck_offer_status CHECK (status IN (
    'DRAFT', 'PENDING_APPROVAL', 'NEEDS_REVISION', 'APPROVED', 'SENT', 'ACCEPTED', 'DECLINED',
    'EXPIRED', 'WITHDRAWN', 'REJECTED'));

ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_version_no;
ALTER TABLE offer ADD CONSTRAINT ck_offer_version_no CHECK (version_no >= 1);

-- ck_offer_sealed_matches_issued and ck_offer_withdraw_reason are added after the backfill in
-- section 6: PostgreSQL validates a new CHECK against existing rows, and until the backfill has
-- stamped sealed_at on the already-issued offers those rows would not satisfy it.

CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_case_version
    ON offer(offer_case_id, version_no) WHERE offer_case_id IS NOT NULL;

-- At most one live version per case: a replacement may only be created after the previous one is
-- withdrawn, expired or answered. Quarantined legacy rows are excluded for the reason given on
-- ux_offer_case_open_application above.
CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_case_single_active_version
    ON offer(offer_case_id)
    WHERE offer_case_id IS NOT NULL
      AND deleted_at IS NULL
      AND legacy_review_required = FALSE
      AND status IN ('DRAFT', 'PENDING_APPROVAL', 'NEEDS_REVISION', 'APPROVED', 'SENT');

CREATE INDEX IF NOT EXISTS ix_offer_offer_case ON offer(offer_case_id);

-- ---------------------------------------------------------------------------------------------
-- 2. Transition log
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS offer_transition_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    offer_case_id BIGINT,
    version_no INTEGER,
    aggregate_version BIGINT,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    actor_user_id BIGINT,
    actor_role VARCHAR(32),
    reason VARCHAR(500),
    admin_override BOOLEAN NOT NULL DEFAULT FALSE,
    correlation_id VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_offer_transition_override_reason
        CHECK (admin_override = FALSE OR reason IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_offer_transition_log_offer
    ON offer_transition_log(offer_id, created_at);
CREATE INDEX IF NOT EXISTS ix_offer_transition_log_case
    ON offer_transition_log(offer_case_id, created_at);

-- ---------------------------------------------------------------------------------------------
-- 3. Sealed-version immutability
--
-- Once a version has been issued, its terms are what the candidate was given. Only the outcome
-- columns may still move (the response, expiry, withdrawal and bookkeeping). Enforcing this in the
-- database rather than only in the service is the point: an admin console, a repair script or a
-- future code path cannot quietly rewrite a document somebody has already accepted.
-- ---------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION offer_sealed_version_is_immutable() RETURNS trigger AS $trigger$
BEGIN
    IF OLD.sealed_at IS NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.salary_offered IS DISTINCT FROM OLD.salary_offered
       OR NEW.contract_type_id IS DISTINCT FROM OLD.contract_type_id
       OR NEW.start_date IS DISTINCT FROM OLD.start_date
       OR NEW.probation_months IS DISTINCT FROM OLD.probation_months
       OR NEW.benefits IS DISTINCT FROM OLD.benefits
       OR NEW.allowance IS DISTINCT FROM OLD.allowance
       OR NEW.candidate_visible_note IS DISTINCT FROM OLD.candidate_visible_note
       OR NEW.application_id IS DISTINCT FROM OLD.application_id
       OR NEW.candidate_id IS DISTINCT FROM OLD.candidate_id
       OR NEW.offer_case_id IS DISTINCT FROM OLD.offer_case_id
       OR NEW.version_no IS DISTINCT FROM OLD.version_no
       OR NEW.issued_at IS DISTINCT FROM OLD.issued_at
       OR NEW.sealed_at IS DISTINCT FROM OLD.sealed_at
    THEN
        RAISE EXCEPTION
            'Offer version % is sealed; withdraw it and issue a new version instead', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$trigger$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_offer_sealed_version_immutable ON offer;
CREATE TRIGGER trg_offer_sealed_version_immutable
    BEFORE UPDATE ON offer
    FOR EACH ROW EXECUTE FUNCTION offer_sealed_version_is_immutable();

-- ---------------------------------------------------------------------------------------------
-- 4. Migration reporting
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS offer_migration_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_offer_id BIGINT NOT NULL,
    offer_case_id BIGINT,
    legacy_status VARCHAR(32),
    disposition VARCHAR(40) NOT NULL,
    note VARCHAR(500),
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by_user_id BIGINT,
    resolution VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_offer_migration_disposition CHECK (disposition IN (
        'MIGRATED', 'AWAITING_BUSINESS_DECISION'))
);

CREATE INDEX IF NOT EXISTS ix_offer_migration_report_disposition
    ON offer_migration_report(disposition);

CREATE TABLE IF NOT EXISTS offer_migration_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_version VARCHAR(20) NOT NULL,
    metric VARCHAR(80) NOT NULL,
    value BIGINT NOT NULL,
    ran_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------------------------
-- 5. Backfill
--
-- Every existing offer becomes version 1 of its own case. No status is reinterpreted:
--   * A legacy APPROVED row stays APPROVED. Before Phase 0 that value also made the offer visible
--     to the candidate, so it *might* have been seen; there is no column that records whether it
--     was. Rewriting it to SENT would claim a publication that may never have happened, and would
--     seal terms HR may still need to correct. It is flagged for a business decision instead.
--   * A legacy REJECTED row stays REJECTED. It recorded an approver refusal, which is now
--     NEEDS_REVISION, but consumers and reports may still key off the old value, so the rename is
--     a reviewed decision rather than a side effect of this migration. The REVISE edge accepts
--     the legacy value so those offers are not stuck in the meantime.
--   * SENT and later rows are sealed, because their terms genuinely are fixed.
-- ---------------------------------------------------------------------------------------------

DO $migration$
DECLARE
    legacy RECORD;
    new_case_id BIGINT;
    case_status TEXT;
    duplicate_open BOOLEAN;
    quarantined INTEGER := 0;
BEGIN
    FOR legacy IN
        -- Newest first, so when an application carries several live offers the most recent one
        -- keeps the clean case and the older ones are the quarantined duplicates.
        SELECT o.* FROM offer o
         WHERE o.offer_case_id IS NULL
         ORDER BY o.created_at DESC NULLS LAST, o.id DESC
    LOOP
        case_status := CASE legacy.status::TEXT
                           WHEN 'ACCEPTED' THEN 'CLOSED_ACCEPTED'
                           WHEN 'DECLINED' THEN 'CLOSED_DECLINED'
                           WHEN 'EXPIRED' THEN 'CLOSED_EXPIRED'
                           WHEN 'WITHDRAWN' THEN 'CLOSED_WITHDRAWN'
                           WHEN 'REJECTED' THEN 'CLOSED_CANCELLED'
                           ELSE 'OPEN'
                       END;
        -- A soft-deleted draft is not an open negotiation and must not block a new one.
        IF legacy.deleted_at IS NOT NULL AND case_status = 'OPEN' THEN
            case_status := 'CLOSED_CANCELLED';
        END IF;

        duplicate_open := case_status = 'OPEN' AND EXISTS (
            SELECT 1 FROM offer_case c
             WHERE c.application_id = legacy.application_id
               AND c.status = 'OPEN'
               AND c.legacy_review_required = FALSE);
        IF duplicate_open THEN
            quarantined := quarantined + 1;
        END IF;

        INSERT INTO offer_case(
            application_id, department_id, assigned_recruiter_id, candidate_id,
            candidate_name_snapshot, status, current_offer_id, version_counter, closed_at,
            legacy_review_required, version, created_at, updated_at)
        VALUES (
            legacy.application_id, legacy.department_id, legacy.assigned_recruiter_id,
            legacy.candidate_id, legacy.candidate_name_snapshot, case_status, legacy.id, 1,
            CASE WHEN case_status = 'OPEN' THEN NULL ELSE now() END,
            duplicate_open, 0, COALESCE(legacy.created_at, now()), now())
        RETURNING id INTO new_case_id;

        UPDATE offer
           SET offer_case_id = new_case_id,
               version_no = 1,
               legacy_review_required = duplicate_open,
               approved_at = CASE
                   WHEN status::TEXT IN ('APPROVED', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')
                   THEN COALESCE(approved_at, issued_at, updated_at) ELSE approved_at END,
               submitted_at = CASE
                   WHEN status::TEXT <> 'DRAFT'
                   THEN COALESCE(submitted_at, created_at) ELSE submitted_at END,
               -- Only rows that really were published are frozen.
               sealed_at = CASE
                   WHEN status::TEXT IN ('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')
                   THEN COALESCE(sealed_at, issued_at, updated_at, now()) ELSE sealed_at END,
               issued_at = CASE
                   WHEN status::TEXT IN ('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')
                   THEN COALESCE(issued_at, updated_at, now()) ELSE issued_at END
         WHERE id = legacy.id;

        INSERT INTO offer_transition_log(
            offer_id, offer_case_id, version_no, aggregate_version, from_status, to_status,
            action, actor_user_id, actor_role, reason, admin_override, created_at)
        VALUES (legacy.id, new_case_id, 1, legacy.version, legacy.status::TEXT,
                legacy.status::TEXT, 'MIGRATE', NULL, 'SYSTEM',
                'Phase 1 backfill: existing offer became version 1 of its case', FALSE, now());

        INSERT INTO offer_migration_report(
            source_offer_id, offer_case_id, legacy_status, disposition, note)
        VALUES (
            legacy.id, new_case_id, legacy.status::TEXT,
            CASE WHEN duplicate_open OR legacy.status::TEXT IN ('APPROVED', 'REJECTED')
                 THEN 'AWAITING_BUSINESS_DECISION' ELSE 'MIGRATED' END,
            left(concat_ws(' ',
                CASE WHEN duplicate_open THEN
                    'The application already had another live offer. This one is quarantined out '
                    || 'of the one-open-case-per-application rule until HR decides which offer '
                    || 'stands; the other is withdrawn or the duplicate is deleted.' END,
                CASE legacy.status::TEXT
                    WHEN 'APPROVED' THEN
                        'Legacy APPROVED also meant candidate-visible. Confirm with HR whether '
                        || 'this offer was actually communicated: if it was, withdraw and reissue '
                        || 'it so a sealed version exists; if it was not, HR issues it normally.'
                    WHEN 'REJECTED' THEN
                        'Legacy REJECTED recorded an approver refusal, equivalent to '
                        || 'NEEDS_REVISION. Confirm no consumer or report depends on the old '
                        || 'value before renaming it.'
                    ELSE NULL
                END), 500));
    END LOOP;

    INSERT INTO offer_migration_summary(migration_version, metric, value)
    VALUES ('V5', 'offer_rows', (SELECT count(*) FROM offer)),
           ('V5', 'offer_cases_created', (SELECT count(*) FROM offer_case)),
           ('V5', 'sealed_versions', (SELECT count(*) FROM offer WHERE sealed_at IS NOT NULL)),
           ('V5', 'quarantined_duplicate_open_cases', quarantined),
           ('V5', 'awaiting_business_decision',
            (SELECT count(*) FROM offer_migration_report
              WHERE disposition = 'AWAITING_BUSINESS_DECISION'));
END
$migration$;

-- ---------------------------------------------------------------------------------------------
-- 6. Invariants that only hold once the backfill has run
--
-- Adding these earlier would fail: PostgreSQL validates a new CHECK against every existing row,
-- and the already-issued offers only get their sealed_at above.
-- ---------------------------------------------------------------------------------------------

-- A version cannot be reported as issued to the candidate without being sealed, and cannot be
-- sealed without having been issued. This is the pair the immutability trigger relies on.
ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_sealed_matches_issued;
ALTER TABLE offer ADD CONSTRAINT ck_offer_sealed_matches_issued CHECK (
    status NOT IN ('SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')
    OR (sealed_at IS NOT NULL AND issued_at IS NOT NULL));

ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_withdraw_reason;
ALTER TABLE offer ADD CONSTRAINT ck_offer_withdraw_reason CHECK (
    status <> 'WITHDRAWN' OR withdraw_reason IS NOT NULL);
