-- Phase 6, P6.5 to P6.7: the end of an offer's life.
--
-- Four things this adds, in the order the business needs them:
--
--   1. Who answered, on the offer row itself. The transition log already knows, but "which offers
--      did this candidate answer" should not require a join to a log table.
--   2. Every deadline extension, as its own append-only row. Section 11.6 requires extensions to be
--      audited, and a counter alone cannot say what the deadline was before.
--   3. One replacement per withdrawn version, enforced by an index rather than by hoping two
--      recruiters never press reissue at the same moment.
--   4. The sealing trigger extended to the section 10 terms V6 added. V5 froze the terms that
--      existed in V5; V6 added twenty-four more and did not extend the trigger, so until now the
--      currency, salary type or work location of a letter a candidate already holds could still be
--      edited. That is the hole this closes, and the reason this migration is not merely additive.

-- ---------------------------------------------------------------------------------------------
-- 1. P6.5 - the candidate's answer, attributable
-- ---------------------------------------------------------------------------------------------

-- Nullable: only an answered offer has an answerer, and an offer that expired has none at all.
ALTER TABLE offer ADD COLUMN IF NOT EXISTS candidate_responded_by_user_id BIGINT;

COMMENT ON COLUMN offer.candidate_responded_by_user_id IS
    'User account that accepted or declined. Not the candidate id: the audit question is which login acted, and one candidate profile can outlive an account.';

-- An accepted or declined offer must say when it was answered. NOT VALID because rows answered
-- before this column existed cannot be backfilled with a time nobody recorded - inventing one
-- would be worse than admitting it is unknown - while every new answer is checked.
ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_response_recorded;
ALTER TABLE offer ADD CONSTRAINT ck_offer_response_recorded CHECK (
    status NOT IN ('ACCEPTED', 'DECLINED') OR candidate_responded_at IS NOT NULL) NOT VALID;

-- Section 11.5: a decline always carries a reason. Same NOT VALID reasoning - legacy declines have
-- no reason id because nothing ever asked for one.
ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_decline_reason_required;
ALTER TABLE offer ADD CONSTRAINT ck_offer_decline_reason_required CHECK (
    status <> 'DECLINED' OR decline_reason_id IS NOT NULL) NOT VALID;

-- Section 11.6: an expired offer records when it expired. The scheduler stamps it; a missing value
-- means something wrote EXPIRED without going through the state machine.
ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_expired_at_recorded;
ALTER TABLE offer ADD CONSTRAINT ck_offer_expired_at_recorded CHECK (
    status <> 'EXPIRED' OR expired_at IS NOT NULL) NOT VALID;

ALTER TABLE offer DROP CONSTRAINT IF EXISTS ck_offer_deadline_extension_count;
ALTER TABLE offer ADD CONSTRAINT ck_offer_deadline_extension_count
    CHECK (deadline_extension_count >= 0);

-- The expiry sweep asks one question every pass: which sent offers are past their deadline. A
-- partial index keeps that a lookup over a handful of live rows rather than a scan that grows with
-- every offer the company has ever made.
CREATE INDEX IF NOT EXISTS ix_offer_due_expiry
    ON offer(response_deadline)
    WHERE status = 'SENT' AND deleted_at IS NULL AND response_deadline IS NOT NULL;

-- Reconciliation (P6.7) reads by outcome.
CREATE INDEX IF NOT EXISTS ix_offer_status_live
    ON offer(status) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- 2. P6.6 - every deadline extension, kept
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS offer_deadline_extension (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL REFERENCES offer(id),
    -- 1 for the first extension of this version, so a row is identifiable without a timestamp.
    extension_no INTEGER NOT NULL,
    previous_deadline TIMESTAMP WITHOUT TIME ZONE,
    new_deadline TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason VARCHAR(500) NOT NULL,
    extended_by_user_id BIGINT NOT NULL,
    extended_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ck_offer_deadline_extension_no CHECK (extension_no >= 1),
    -- An "extension" that moves the deadline earlier is a shortening, and a candidate whose window
    -- silently narrows after they were told a date has been treated unfairly.
    CONSTRAINT ck_offer_deadline_extension_forward CHECK (
        previous_deadline IS NULL OR new_deadline > previous_deadline)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_deadline_extension_no
    ON offer_deadline_extension(offer_id, extension_no);

CREATE INDEX IF NOT EXISTS ix_offer_deadline_extension_offer
    ON offer_deadline_extension(offer_id, extended_at);

-- Append-only, for the same reason the approval snapshots are: "we gave them until the 20th" is a
-- statement about a promise made to a person, and a promise that can be quietly rewritten later is
-- not evidence of anything.
CREATE OR REPLACE FUNCTION offer_deadline_extension_is_append_only() RETURNS trigger AS $body$
BEGIN
    RAISE EXCEPTION
        'offer_deadline_extension is append-only; the extension history of offer % cannot be changed or removed',
        COALESCE(OLD.offer_id, NEW.offer_id)
        USING ERRCODE = 'restrict_violation';
END;
$body$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_offer_deadline_extension_append_only ON offer_deadline_extension;
CREATE TRIGGER trg_offer_deadline_extension_append_only
    BEFORE UPDATE OR DELETE ON offer_deadline_extension
    FOR EACH ROW EXECUTE FUNCTION offer_deadline_extension_is_append_only();

-- ---------------------------------------------------------------------------------------------
-- 3. P6.6 - one replacement per withdrawn version
--
-- Two recruiters reissuing the same withdrawn offer at the same moment would produce two live
-- versions of one letter, and the candidate would have no way to tell which one is theirs.
-- ux_offer_case_single_active_version already forbids two active versions in a case; this forbids
-- the same predecessor being replaced twice even across cases.
-- ---------------------------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS ux_offer_replaces_version_once
    ON offer(replaces_offer_version_id)
    WHERE replaces_offer_version_id IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- 4. Sealing extended to the section 10 terms
--
-- V5 wrote this function against the columns that existed then. V6 added the section 10 term set
-- and left the function alone, so an issued letter's currency, salary type, probation salary, work
-- location or contact person could still be changed after the candidate had it in hand. The letter
-- itself is immutable (offer_artifact), which means a database edit could not change the PDF but
-- could make the row disagree with it - the worst of both, because each looks authoritative alone.
--
-- response_deadline and deadline_extension_count stay mutable on purpose: section 11.6 lets HR
-- extend a deadline on an offer already with the candidate, and every extension is recorded above.
-- ---------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION offer_sealed_version_is_immutable() RETURNS trigger AS $trigger$
BEGIN
    IF OLD.sealed_at IS NULL THEN
        RETURN NEW;
    END IF;
    IF NEW.salary_offered IS DISTINCT FROM OLD.salary_offered
       OR NEW.contract_type_id IS DISTINCT FROM OLD.contract_type_id
       OR NEW.start_date IS DISTINCT FROM OLD.start_date
       OR NEW.probation_months IS DISTINCT FROM OLD.probation_months
       OR NEW.benefits IS DISTINCT FROM OLD.benefits
       OR NEW.allowance IS DISTINCT FROM OLD.allowance
       OR NEW.candidate_visible_note IS DISTINCT FROM OLD.candidate_visible_note
       OR NEW.application_id IS DISTINCT FROM OLD.application_id
       OR NEW.candidate_id IS DISTINCT FROM OLD.candidate_id
       OR NEW.offer_case_id IS DISTINCT FROM OLD.offer_case_id
       OR NEW.version_no IS DISTINCT FROM OLD.version_no
       OR NEW.issued_at IS DISTINCT FROM OLD.issued_at
       OR NEW.sealed_at IS DISTINCT FROM OLD.sealed_at
       -- 10.1 candidate and job
       OR NEW.candidate_email_snapshot IS DISTINCT FROM OLD.candidate_email_snapshot
       OR NEW.candidate_phone_snapshot IS DISTINCT FROM OLD.candidate_phone_snapshot
       OR NEW.job_title_snapshot IS DISTINCT FROM OLD.job_title_snapshot
       OR NEW.department_name_snapshot IS DISTINCT FROM OLD.department_name_snapshot
       OR NEW.hiring_manager_id IS DISTINCT FROM OLD.hiring_manager_id
       OR NEW.hiring_manager_name_snapshot IS DISTINCT FROM OLD.hiring_manager_name_snapshot
       -- 10.2 employment terms
       OR NEW.work_location_id IS DISTINCT FROM OLD.work_location_id
       OR NEW.work_location_snapshot IS DISTINCT FROM OLD.work_location_snapshot
       OR NEW.work_arrangement IS DISTINCT FROM OLD.work_arrangement
       OR NEW.working_hours IS DISTINCT FROM OLD.working_hours
       OR NEW.direct_manager_id IS DISTINCT FROM OLD.direct_manager_id
       OR NEW.direct_manager_name_snapshot IS DISTINCT FROM OLD.direct_manager_name_snapshot
       OR NEW.employment_conditions IS DISTINCT FROM OLD.employment_conditions
       -- 10.3 income and benefits
       OR NEW.salary_type IS DISTINCT FROM OLD.salary_type
       OR NEW.currency IS DISTINCT FROM OLD.currency
       OR NEW.pay_cycle IS DISTINCT FROM OLD.pay_cycle
       OR NEW.probation_salary IS DISTINCT FROM OLD.probation_salary
       OR NEW.bonus_kpi IS DISTINCT FROM OLD.bonus_kpi
       OR NEW.hm_proposed_salary IS DISTINCT FROM OLD.hm_proposed_salary
       -- 10.4 response information
       OR NEW.contact_person_name IS DISTINCT FROM OLD.contact_person_name
       OR NEW.contact_person_email IS DISTINCT FROM OLD.contact_person_email
       OR NEW.contact_person_phone IS DISTINCT FROM OLD.contact_person_phone
       OR NEW.effective_conditions IS DISTINCT FROM OLD.effective_conditions
    THEN
        RAISE EXCEPTION
            'Offer version % is sealed; withdraw it and issue a new version instead', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$trigger$ LANGUAGE plpgsql;

-- The trigger itself is unchanged and still bound to the function; recreated so a database where
-- someone dropped it during an incident comes back consistent.
DROP TRIGGER IF EXISTS trg_offer_sealed_version_immutable ON offer;
CREATE TRIGGER trg_offer_sealed_version_immutable
    BEFORE UPDATE ON offer
    FOR EACH ROW EXECUTE FUNCTION offer_sealed_version_is_immutable();
