import type { CatalogConfig } from "./types";

export const catalogConfigs: CatalogConfig[] = [
    {
        key: "departments",
        tabLabel: "Phòng ban",
        title: "Phòng ban",
        endpoint: "/masterdata/departments",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên phòng ban", type: "text", required: true },
            { name: "description", label: "Mô tả", type: "textarea" },
        ],
    },
    {
        key: "jobTitles",
        tabLabel: "Chức vụ",
        title: "Chức vụ",
        endpoint: "/masterdata/job-titles",
        primaryField: "name",
        fields: [{ name: "name", label: "Tên chức vụ", type: "text", required: true }],
    },
    {
        key: "jobLevels",
        tabLabel: "Cấp bậc công việc",
        title: "Cấp bậc công việc",
        endpoint: "/masterdata/job-levels",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên cấp bậc", type: "text", required: true },
            { name: "orderNo", label: "Thứ tự", type: "number", required: true },
        ],
    },
    {
        key: "workLocations",
        tabLabel: "Địa điểm làm việc",
        title: "Địa điểm làm việc",
        endpoint: "/masterdata/work-locations",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên địa điểm", type: "text", required: true },
            { name: "address", label: "Địa chỉ", type: "text" },
        ],
    },
    {
        key: "employmentTypes",
        tabLabel: "Loại hình làm việc",
        title: "Loại hình làm việc",
        endpoint: "/masterdata/employment-types",
        primaryField: "name",
        fields: [{ name: "name", label: "Tên loại hình", type: "text", required: true }],
    },
    {
        key: "contractTypes",
        tabLabel: "Loại hợp đồng",
        title: "Loại hợp đồng",
        endpoint: "/masterdata/contract-types",
        primaryField: "name",
        fields: [{ name: "name", label: "Tên loại hợp đồng", type: "text", required: true }],
    },
    {
        key: "recruitmentSources",
        tabLabel: "Nguồn tuyển dụng",
        title: "Nguồn tuyển dụng",
        endpoint: "/masterdata/recruitment-sources",
        primaryField: "name",
        fields: [{ name: "name", label: "Tên nguồn", type: "text", required: true }],
    },
    {
        key: "skills",
        tabLabel: "Kỹ năng",
        title: "Kỹ năng",
        endpoint: "/masterdata/skills",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên kỹ năng", type: "text", required: true },
            { name: "category", label: "Nhóm kỹ năng", type: "text" },
        ],
    },
    {
        key: "educationLevels",
        tabLabel: "Trình độ học vấn",
        title: "Trình độ học vấn",
        endpoint: "/masterdata/education-levels",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên trình độ", type: "text", required: true },
            { name: "orderNo", label: "Thứ tự", type: "number", required: true },
        ],
    },
    {
        key: "experienceLevels",
        tabLabel: "Mức kinh nghiệm",
        title: "Mức kinh nghiệm",
        endpoint: "/masterdata/experience-levels",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên mức kinh nghiệm", type: "text", required: true },
            { name: "minYears", label: "Số năm tối thiểu", type: "number", required: true },
            { name: "maxYears", label: "Số năm tối đa", type: "number", required: true },
        ],
    },
    {
        key: "rejectionReasons",
        tabLabel: "Lý do từ chối",
        title: "Lý do từ chối",
        endpoint: "/masterdata/rejection-reasons",
        primaryField: "name",
        fields: [{ name: "name", label: "Lý do từ chối", type: "text", required: true }],
    },
    {
        key: "recruitmentStatuses",
        tabLabel: "Trạng thái tuyển dụng",
        title: "Trạng thái tuyển dụng",
        endpoint: "/masterdata/recruitment-statuses",
        primaryField: "name",
        fields: [
            { name: "name", label: "Tên trạng thái", type: "text", required: true },
            { name: "orderNo", label: "Thứ tự", type: "number", required: true },
        ],
    },
    {
        key: "emailTemplates",
        tabLabel: "Mẫu email",
        title: "Mẫu email",
        endpoint: "/masterdata/email-templates",
        primaryField: "code",
        fields: [
            { name: "code", label: "Mã mẫu (vd: INTERVIEW_INVITATION)", type: "text", required: true },
            { name: "subject", label: "Tiêu đề email", type: "text", required: true },
            { name: "body", label: "Nội dung email", type: "textarea", required: true, hideInTable: true },
        ],
    },
];