-- ---------------------------------------------------------------------------------------------
-- 0. Baseline for `job_requisition`, paying off a debt Phase 0 left in this service.
--
-- P0.6 gave interview, offer, application and notification a Flyway baseline and switched them to
-- `ddl-auto: validate`. recruitment-service was not in that scope: it still runs `ddl-auto: update`,
-- and V1/V2 are written defensively (`IF to_regclass(...) IS NOT NULL`) precisely because no
-- migration here has ever created a table.
--
-- V3 is the first one that cannot be defensive. The ledger's foreign key to `job_requisition` is
-- what guarantees a reservation can never outlive the requisition it counts against, and that is
-- the single invariant this whole table exists to protect -- so it is not being dropped to keep the
-- migration optional. But Flyway runs before Hibernate, so on a database where Hibernate has not
-- yet created the table, V3 would fail and the service would never start.
--
-- Hence this section: create the table only if it is absent. On every existing database it is a
-- no-op. On a fresh one it gives V3 something to point at, and Hibernate reconciles the rest of the
-- schema afterwards as it does today.
--
-- This is NOT a substitute for giving recruitment-service a real P0.6 baseline and `validate`. It
-- is the smallest thing that makes Phase 5 deployable without weakening the ledger.
-- ---------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS job_requisition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    job_title_id BIGINT NOT NULL,
    job_level_id BIGINT,
    employment_type_id BIGINT,
    work_location_id BIGINT,
    work_arrangement VARCHAR(255),
    quantity INTEGER NOT NULL,
    reason VARCHAR(255),
    priority VARCHAR(255),
    requester_id BIGINT NOT NULL,
    approver_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    description TEXT,
    requirements TEXT,
    benefits TEXT,
    experience_required VARCHAR(255),
    budget NUMERIC(38,2),
    expected_salary_min NUMERIC(38,2),
    expected_salary_max NUMERIC(38,2),
    approved_salary_min NUMERIC(38,2),
    approved_salary_max NUMERIC(38,2),
    expected_start_date DATE,
    hr_note TEXT,
    note TEXT,
    reject_reason VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- ---------------------------------------------------------------------------------------------
-- 1. The Phase 5 ledger
-- ---------------------------------------------------------------------------------------------

-- P5.4: append-only headcount allocation ledger. job_requisition.quantity remains the target;
-- there is intentionally no mutable hired_count/reserved_count column to drift out of sync.
CREATE TABLE headcount_reservation (
    id UUID PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    selection_decision_id BIGINT NOT NULL,
    request_id UUID NOT NULL,
    status VARCHAR(16) NOT NULL,
    lease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    filled_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,
    release_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_headcount_reservation_requisition
        FOREIGN KEY (requisition_id) REFERENCES job_requisition(id) ON DELETE RESTRICT,
    CONSTRAINT uq_headcount_reservation_selection_decision UNIQUE (selection_decision_id),
    CONSTRAINT ck_headcount_reservation_status
        CHECK (status IN ('PENDING', 'RESERVED', 'FILLED', 'RELEASED')),
    CONSTRAINT ck_headcount_reservation_confirmed
        CHECK (status NOT IN ('RESERVED', 'FILLED') OR confirmed_at IS NOT NULL),
    CONSTRAINT ck_headcount_reservation_filled
        CHECK (status <> 'FILLED' OR filled_at IS NOT NULL),
    CONSTRAINT ck_headcount_reservation_released
        CHECK (status <> 'RELEASED' OR released_at IS NOT NULL)
);

-- Counts and all capacity checks are scoped by requisition/status.
CREATE INDEX ix_headcount_reservation_requisition_status
    ON headcount_reservation (requisition_id, status);
CREATE INDEX ix_headcount_reservation_request
    ON headcount_reservation (request_id);
-- A bounded reconciler only scans expired PENDING leases; terminal audit rows stay cheap.
CREATE INDEX ix_headcount_reservation_pending_lease
    ON headcount_reservation (lease_expires_at, id)
    WHERE status = 'PENDING';

-- Durable idempotency inbox for accept/decline/expired/withdrawn offer outcomes.
CREATE TABLE headcount_outcome (
    outcome_id UUID PRIMARY KEY,
    reservation_id UUID NOT NULL,
    action VARCHAR(16) NOT NULL,
    reason VARCHAR(500),
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_headcount_outcome_reservation
        FOREIGN KEY (reservation_id) REFERENCES headcount_reservation(id) ON DELETE RESTRICT,
    CONSTRAINT ck_headcount_outcome_action CHECK (action IN ('CONSUME', 'RELEASE')),
    CONSTRAINT ck_headcount_outcome_release_reason
        CHECK (action <> 'RELEASE' OR reason IS NOT NULL)
);

CREATE INDEX ix_headcount_outcome_reservation
    ON headcount_outcome (reservation_id, processed_at);

COMMENT ON COLUMN headcount_reservation.selection_decision_id IS
    'Global idempotency key owned by interview-service SelectionRoundCandidate';
COMMENT ON COLUMN headcount_outcome.outcome_id IS
    'Global idempotency key supplied by offer-service outcome processing';
