package iuh.fit.se.notification.notification;

public enum NotificationType {
    REQUISITION_PENDING_APPROVAL,
    APPLICATION_CREATED,
    APPLICATION_STAGE_CHANGED,
    APPLICATION_REJECTED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CONFIRMED,
    INTERVIEW_REMINDER,
    EVALUATION_INCOMPLETE_REMINDER,
    OFFER_PENDING_CONFIRMATION,
    OFFER_READY_FOR_CANDIDATE,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    APPLICATION_COMMENT_MENTION,
    APPLICATION_STALE_REMINDER
}