/**
 * Chuỗi hiển thị dùng chung (quy tắc 7 của CLAUDE.md). Chuỗi chỉ thuộc về một màn thì đặt
 * dưới khóa của màn đó khi làm màn ấy.
 */
export const STRINGS = {
  common: {
    retry: "Thử lại",
    back: "Quay lại",
    close: "Đóng",
    clearSearch: "Xóa nội dung tìm kiếm",
    showPassword: "Hiện mật khẩu",
    hidePassword: "Ẩn mật khẩu",
    required: " *",
    loading: "Đang tải",
  },
  brand: {
    mark: "A",
    name: "ATS",
    tagline: "HỆ THỐNG TUYỂN DỤNG",
  },
  auth: {
    otpLabel: "Mã OTP",
    otpA11y: "Mã xác minh gồm 6 chữ số",
    resend: "Gửi lại mã",
    resendIn: (s: number) => `Gửi lại sau ${s}s`,
    backToLogin: "Quay lại đăng nhập",
    validation: {
      emailRequired: "Vui lòng nhập email",
      emailInvalid: "Email không hợp lệ",
      passwordRequired: "Vui lòng nhập mật khẩu",
      passwordMin: "Mật khẩu tối thiểu 8 ký tự",
      passwordMax: "Mật khẩu tối đa 72 ký tự",
      confirmRequired: "Vui lòng nhập lại mật khẩu",
      confirmMismatch: "Mật khẩu nhập lại không khớp",
      fullNameRequired: "Vui lòng nhập họ tên",
      otpFormat: "Mã OTP gồm đúng 6 chữ số",
    },
    login: {
      title: "Đăng nhập",
      subtitle: "Sử dụng email và mật khẩu của bạn.",
      email: "Email",
      password: "Mật khẩu",
      forgot: "Quên mật khẩu?",
      submit: "Đăng nhập",
      candidatePrompt: "Bạn là ứng viên?",
      createAccount: "Tạo tài khoản ứng viên",
      failed: "Đăng nhập thất bại",
      verifiedNotice: "Xác minh thành công, mời đăng nhập.",
      resetNotice: "Mật khẩu đã được cập nhật, mời đăng nhập.",
    },
    register: {
      title: "Đăng ký ứng viên",
      subtitle: "Tạo tài khoản để nộp hồ sơ và theo dõi tiến độ tuyển dụng.",
      fullName: "Họ và tên",
      email: "Email",
      phone: "Số điện thoại (không bắt buộc)",
      password: "Mật khẩu",
      passwordHint: "Tối thiểu 8 ký tự",
      confirm: "Nhập lại mật khẩu",
      submit: "Đăng ký",
      haveAccount: "Đã có tài khoản?",
      login: "Đăng nhập",
      failed: "Đăng ký thất bại",
    },
    verify: {
      title: "Xác minh email",
      subtitle: (email?: string) =>
        `Nhập mã gồm 6 chữ số đã gửi tới ${email || "email của bạn"}.`,
      submit: "Xác minh",
      notReceived: "Chưa nhận được mã?",
      missingEmail: "Thiếu email cần xác minh, vui lòng đăng ký lại.",
      failed: "Xác minh thất bại",
      resent: "Đã gửi lại mã xác minh, vui lòng kiểm tra hộp thư.",
      resendFailed: "Không gửi lại được mã",
    },
    forgot: {
      title: "Quên mật khẩu",
      subtitle: "Nhập email để nhận mã OTP đặt lại mật khẩu.",
      email: "Email",
      submit: "Gửi mã OTP",
      failed: "Không gửi được yêu cầu",
    },
    reset: {
      title: "Đặt lại mật khẩu",
      // Backend trả cùng một câu dù email có tồn tại hay không → KHÔNG khẳng định đã gửi.
      subtitle: (email?: string) =>
        email
          ? `Nếu ${email} đã đăng ký, mã OTP gồm 6 chữ số đã được gửi tới hộp thư đó. Nhập mã và mật khẩu mới.`
          : "Nếu email tồn tại trong hệ thống, mã OTP gồm 6 chữ số đã được gửi tới hộp thư. Nhập mã và mật khẩu mới.",
      email: "Email",
      newPassword: "Mật khẩu mới",
      confirm: "Nhập lại mật khẩu mới",
      submit: "Đặt lại mật khẩu",
      notReceived: "Không nhận được?",
      needEmail: "Vui lòng nhập email trước khi gửi lại mã.",
      resent: "Nếu email tồn tại, mã OTP mới đã được gửi đi.",
      resendFailed: "Không gửi lại được mã",
      failed: "Đặt lại mật khẩu thất bại",
    },
  },
  errorState: {
    title: "Không tải được dữ liệu",
    fallback: "Kiểm tra kết nối mạng rồi thử lại.",
  },
  tabs: {
    candidate: {
      jobs: "Việc làm",
      applications: "Đơn của tôi",
      interviews: "Lịch PV",
      profile: "Hồ sơ",
    },
    hm: {
      todo: "Cần duyệt",
      interviews: "Phỏng vấn",
    },
    hr: {
      home: "Tổng quan",
      requisitions: "Yêu cầu TD",
      applications: "Hồ sơ",
    },
  },
  placeholder: {
    session: "Phiên đăng nhập",
    email: "Email",
    role: "Vai trò",
    department: "Phòng ban",
    signOut: "Đăng xuất",
  },
  roles: {
    COMPANY_ADMIN: "Quản trị doanh nghiệp",
    RECRUITER: "Chuyên viên tuyển dụng",
    HIRING_MANAGER: "Quản lý tuyển dụng",
    CANDIDATE: "Ứng viên",
  },

  /** Nhãn trạng thái — chỉ đọc qua `src/lib/status.ts`, đừng lấy thẳng ở màn hình. */
  status: {
    stage: {
      APPLIED: "Ứng tuyển",
      CV_SCREENING: "Sàng lọc CV",
      HR_SCREENING: "Sàng lọc HR",
      TECHNICAL_INTERVIEW: "PV kỹ thuật",
      HR_INTERVIEW: "PV HR",
      FINAL_INTERVIEW: "PV vòng cuối",
      OFFER: "Đề nghị nhận việc",
      HIRED: "Đã tuyển dụng",
      REJECTED: "Từ chối",
      CUSTOM: "Vòng khác",
    },
    interview: {
      SCHEDULED: "Chờ HM xác nhận",
      HM_RESCHEDULE_PROPOSED: "HM đề xuất đổi giờ",
      HM_CONFIRMED: "Chờ ứng viên xác nhận",
      CANDIDATE_CONFIRMED: "Đã xác nhận",
      EVALUATION_PENDING: "Chờ đánh giá",
      COMPLETED: "Hoàn tất",
      NO_SHOW: "Vắng mặt",
      CANCELLED: "Đã hủy",
    },
    /** Ứng viên nhìn cùng một trạng thái theo góc của mình. */
    interviewForCandidate: {
      HM_CONFIRMED: "Chờ xác nhận",
      EVALUATION_PENDING: "Đã diễn ra",
      COMPLETED: "Đã diễn ra",
    },
    offer: {
      DRAFT: "Nháp",
      PENDING_APPROVAL: "Chờ duyệt",
      APPROVED: "Đã gửi ứng viên",
      REJECTED: "Không được duyệt",
      ACCEPTED: "Đã nhận việc",
      DECLINED: "Ứng viên từ chối",
    },
    offerForCandidate: {
      APPROVED: "Chờ phản hồi",
      DECLINED: "Đã từ chối",
    },
    requisition: {
      DRAFT: "Nháp",
      PENDING_APPROVAL: "Chờ duyệt",
      APPROVED: "Đã duyệt",
      REJECTED: "Bị từ chối",
      CHANGES_REQUESTED: "Cần chỉnh sửa",
    },
    posting: {
      DRAFT: "Nháp",
      EDITING: "Đang sửa",
      APPROVED: "Đã duyệt",
      OPEN: "Đang mở",
      PAUSED: "Tạm dừng",
      CLOSED: "Đã đóng",
    },
    unknown: "Không rõ",
  },
} as const;
