/**
 * Chuỗi hiển thị dùng chung (quy tắc 7 của CLAUDE.md). Chuỗi chỉ thuộc về một màn thì đặt
 * dưới khóa của màn đó khi làm màn ấy.
 */
export const STRINGS = {
  common: {
    retry: "Thử lại",
    back: "Quay lại",
    close: "Đóng",
    clearSearch: "Xóa nội dung tìm kiếm",
    showPassword: "Hiện mật khẩu",
    hidePassword: "Ẩn mật khẩu",
    required: " *",
    loading: "Đang tải",
  },
  brand: {
    mark: "A",
    name: "ATS",
    tagline: "HỆ THỐNG TUYỂN DỤNG",
  },
  auth: {
    otpLabel: "Mã OTP",
    otpA11y: "Mã xác minh gồm 6 chữ số",
    resend: "Gửi lại mã",
    resendIn: (s: number) => `Gửi lại sau ${s}s`,
    backToLogin: "Quay lại đăng nhập",
    validation: {
      emailRequired: "Vui lòng nhập email",
      emailInvalid: "Email không hợp lệ",
      passwordRequired: "Vui lòng nhập mật khẩu",
      passwordMin: "Mật khẩu tối thiểu 8 ký tự",
      passwordMax: "Mật khẩu tối đa 72 ký tự",
      confirmRequired: "Vui lòng nhập lại mật khẩu",
      confirmMismatch: "Mật khẩu nhập lại không khớp",
      fullNameRequired: "Vui lòng nhập họ tên",
      otpFormat: "Mã OTP gồm đúng 6 chữ số",
    },
    login: {
      title: "Đăng nhập",
      subtitle: "Sử dụng email và mật khẩu của bạn.",
      email: "Email",
      password: "Mật khẩu",
      forgot: "Quên mật khẩu?",
      submit: "Đăng nhập",
      candidatePrompt: "Bạn là ứng viên?",
      createAccount: "Tạo tài khoản ứng viên",
      failed: "Đăng nhập thất bại",
      verifiedNotice: "Xác minh thành công, mời đăng nhập.",
      resetNotice: "Mật khẩu đã được cập nhật, mời đăng nhập.",
    },
    register: {
      title: "Đăng ký ứng viên",
      subtitle: "Tạo tài khoản để nộp hồ sơ và theo dõi tiến độ tuyển dụng.",
      fullName: "Họ và tên",
      email: "Email",
      phone: "Số điện thoại (không bắt buộc)",
      password: "Mật khẩu",
      passwordHint: "Tối thiểu 8 ký tự",
      confirm: "Nhập lại mật khẩu",
      submit: "Đăng ký",
      haveAccount: "Đã có tài khoản?",
      login: "Đăng nhập",
      failed: "Đăng ký thất bại",
    },
    verify: {
      title: "Xác minh email",
      subtitle: (email?: string) =>
        `Nhập mã gồm 6 chữ số đã gửi tới ${email || "email của bạn"}.`,
      submit: "Xác minh",
      notReceived: "Chưa nhận được mã?",
      missingEmail: "Thiếu email cần xác minh, vui lòng đăng ký lại.",
      failed: "Xác minh thất bại",
      resent: "Đã gửi lại mã xác minh, vui lòng kiểm tra hộp thư.",
      resendFailed: "Không gửi lại được mã",
    },
    forgot: {
      title: "Quên mật khẩu",
      subtitle: "Nhập email để nhận mã OTP đặt lại mật khẩu.",
      email: "Email",
      submit: "Gửi mã OTP",
      failed: "Không gửi được yêu cầu",
    },
    reset: {
      title: "Đặt lại mật khẩu",
      // Backend trả cùng một câu dù email có tồn tại hay không → KHÔNG khẳng định đã gửi.
      subtitle: (email?: string) =>
        email
          ? `Nếu ${email} đã đăng ký, mã OTP gồm 6 chữ số đã được gửi tới hộp thư đó. Nhập mã và mật khẩu mới.`
          : "Nếu email tồn tại trong hệ thống, mã OTP gồm 6 chữ số đã được gửi tới hộp thư. Nhập mã và mật khẩu mới.",
      email: "Email",
      newPassword: "Mật khẩu mới",
      confirm: "Nhập lại mật khẩu mới",
      submit: "Đặt lại mật khẩu",
      notReceived: "Không nhận được?",
      needEmail: "Vui lòng nhập email trước khi gửi lại mã.",
      resent: "Nếu email tồn tại, mã OTP mới đã được gửi đi.",
      resendFailed: "Không gửi lại được mã",
      failed: "Đặt lại mật khẩu thất bại",
    },
  },
  format: {
    negotiable: "Thỏa thuận",
    million: "triệu",
    perMonth: "/ tháng",
    from: "Từ",
    upTo: "Đến",
    justNow: "Vừa xong",
    minutesAgo: (n: number) => `${n} phút trước`,
    hoursAgo: (n: number) => `${n} giờ trước`,
    daysAgo: (n: number) => `${n} ngày trước`,
    posted: (rel: string) => `Đăng ${rel}`,
    currency: "đ",
    weekdays: ["Chủ Nhật", "Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy"],
    monthShort: (m: number) => `TH ${m}`,
    daysHours: (d: number, h: string) => `${d} ngày ${h} giờ`,
    hoursLeft: (h: number) => `${h} giờ`,
    daysLeft: (d: number) => `Còn ${d} ngày`,
  },
  arrangement: {
    ONSITE: "Tại văn phòng",
    HYBRID: "Kết hợp",
    REMOTE: "Từ xa",
  },
  jobs: {
    title: "Việc làm",
    searchPlaceholder: "Tìm vị trí, phòng ban, nơi làm…",
    all: "Tất cả",
    openCount: (n: number) => `${n} vị trí đang mở`,
    applied: "Đã nộp",
    forYou: "Phù hợp với bạn",
    others: "Vị trí khác",
    skillMatch: (m: number, t: number) => `Khớp ${m}/${t} kỹ năng trong hồ sơ của bạn`,
    salaryShort: (s: string) => s.replace(" triệu", " tr"),
    emptyTitle: "Chưa có vị trí đang tuyển",
    emptyMessage: "Nhà tuyển dụng chưa đăng tin mới. Kéo xuống để tải lại sau ít phút.",
    noMatchTitle: "Không có vị trí phù hợp",
    noMatchMessage: "Thử từ khóa khác hoặc bỏ bộ lọc để xem tất cả vị trí.",
    clearFilters: "Xóa bộ lọc",
  },
  jobDetail: {
    title: "Chi tiết tin",
    salary: "Mức lương",
    experience: "Kinh nghiệm",
    employmentType: "Hình thức",
    location: "Nơi làm việc",
    published: "Ngày đăng",
    description: "Bạn sẽ làm gì",
    requirements: "Bạn cần có",
    benefits: "Quyền lợi",
    process: "Quy trình",
    quickApply: "Ứng tuyển nhanh",
    viewMyApplication: "Đã ứng tuyển · Xem hồ sơ",
    yearsExp: (s: string) => s,
    cvNote: "Khi ứng tuyển, hệ thống dùng CV đang có trong hồ sơ của bạn.",
    notSpecified: "Không yêu cầu",
    source: (name: string) => `Nguồn: ${name}`,
    pickSource: "Chọn nguồn",
    apply: "Ứng tuyển",
    applied: "Đã ứng tuyển",
    viewApplication: "Xem đơn",
    sourceSheetTitle: "Bạn biết tin này từ đâu?",
    sourceSheetSubtitle: "Chọn một nguồn để nhà tuyển dụng biết bạn đến từ đâu.",
    sourceRequired: "Chọn nơi bạn biết tin trước khi ứng tuyển.",
    sourcesError: "Không tải được danh sách nguồn tuyển dụng.",
    success: "Đã nộp đơn. Theo dõi tiến trình ở mục Đơn của tôi.",
    failed: "Nộp đơn thất bại",
    uploadCv: "Tải CV",
    notOpen: "Tin này hiện không nhận hồ sơ.",
  },
  apply: {
    title: "Ứng tuyển",
    cvAttached: "CV gửi kèm",
    cvFromProfile: "Lấy từ hồ sơ của bạn",
    changeCv: "Đổi",
    noCv: "Bạn chưa có CV",
    noCvHint: "Tải CV lên ở mục Tôi trước khi ứng tuyển.",
    uploadCv: "Tải CV",
    source: "Bạn biết tin này từ đâu?",
    sourcePlaceholder: "Chọn nguồn",
    note: "Lời nhắn cho nhà tuyển dụng (không bắt buộc)",
    submit: "Gửi hồ sơ",
  },
  applications: {
    title: "Hồ sơ ứng tuyển",
    meta: (dept: string, date: string) => (dept ? `${dept} · nộp ${date}` : `Nộp ${date}`),
    needSlot: "Cần chọn giờ",
    pickTime: "Chọn giờ",
    inviteInterview: "Mời bạn chọn giờ phỏng vấn",
    confirmInterview: "Nhà tuyển dụng đã hẹn lịch — xác nhận tham gia",
    offerDeclined: "Bạn đã từ chối thư mời",
    all: "Tất cả",
    active: "Đang xử lý",
    ended: "Đã kết thúc",
    appliedOn: (date: string) => `Nộp ${date}`,
    phases: ["Nộp", "Sàng lọc", "PV", "Kết quả"],
    /** Nhãn đầy đủ cho dòng thời gian ở màn chi tiết (canvas N30). */
    timeline: ["Đã nộp hồ sơ", "Sàng lọc hồ sơ", "Phỏng vấn", "Kết quả"],
    note: {
      received: "Hồ sơ đã được tiếp nhận",
      screening: "Nhà tuyển dụng đang xem hồ sơ",
      interview: "Bạn đang ở vòng phỏng vấn",
      interviewAt: (when: string) => `Phỏng vấn ${when}`,
      offer: "Bạn đã nhận được thư mời nhận việc",
      hired: "Chúc mừng, bạn đã trúng tuyển",
      rejected: "Hồ sơ chưa phù hợp với vị trí này",
      rejectedReason: (r: string) => `Hồ sơ chưa phù hợp: ${r}`,
    },
    emptyTitle: "Bạn chưa nộp đơn nào",
    emptyMessage: "Tìm một vị trí phù hợp và ứng tuyển — tiến trình sẽ hiện ở đây.",
    browseJobs: "Xem việc làm",
    noMatchTitle: "Không có đơn trong mục này",
    noMatchMessage: "Chọn \"Tất cả\" để xem mọi đơn của bạn.",
  },
  applicationDetail: {
    title: "Chi tiết đơn",
    progress: "Tiến trình",
    pickInterviewTime: "Chọn giờ phỏng vấn",
    slotInvite: (n: number) => `Mời phỏng vấn · ${n} khung giờ đề xuất`,
    confirmInvite: "Nhà tuyển dụng đã hẹn lịch phỏng vấn",
    stepDone: "Đã qua",
    stepCurrent: "Đang ở bước này",
    stepUpcoming: "Chưa đến",
    rejectedTitle: "Không tiếp tục",
    hiredTitle: "Đã trúng tuyển",
    interview: "Lịch phỏng vấn",
    online: "Trực tuyến",
    offline: "Tại văn phòng",
    openMeeting: "Mở phòng họp",
    offer: "Thư mời nhận việc",
    viewOffer: "Xem thư mời",
    viewJob: "Xem tin tuyển dụng",
  },
  schedule: {
    title: "Chọn giờ",
    subtitle: (minutes?: number) => (minutes ? `${minutes} phút · giờ Việt Nam` : "Giờ Việt Nam"),
    hint: "Chọn giờ bạn rảnh. Nhà tuyển dụng sẽ chốt lịch và báo lại cho bạn.",
    submit: (time: string, day: string) => `Báo rảnh ${time}, ${day}`,
    pickFirst: "Chọn một giờ",
    done: "Đã báo bạn rảnh giờ này. HR sẽ chốt lịch và báo lại.",
    failed: "Không gửi được",
    weekdayShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
    emptyTitle: "Không còn khung giờ cần chọn",
    emptyMessage: "Bạn đã báo hết giờ rảnh. Khi HR chốt lịch, buổi phỏng vấn sẽ hiện ở tab Lịch.",
    back: "Về lịch phỏng vấn",
  },
  interviews: {
    title: "Lịch phỏng vấn",
    pendingTitle: (n: number) => `${n} khung giờ chờ bạn chọn`,
    pendingHint: "Nhà tuyển dụng đề xuất vài khung giờ. Báo giờ bạn rảnh để HR chốt lịch.",
    upcoming: "Sắp tới",
    past: "Đã qua",
    online: "Trực tuyến",
    offline: "Tại văn phòng",
    interviewers: (names: string) => `Người phỏng vấn: ${names}`,
    confirm: "Xác nhận",
    confirmed: "Đã xác nhận tham gia.",
    confirmFailed: "Xác nhận thất bại",
    openMeeting: "Vào phòng",
    jobFallback: "Buổi phỏng vấn",
    slotsTitle: "Chọn giờ bạn rảnh",
    slotsHint: "Nhà tuyển dụng đề xuất các khung giờ dưới đây. Báo giờ bạn rảnh, HR sẽ chốt lịch.",
    available: "Tôi rảnh",
    availableDone: "Đã báo bạn rảnh giờ này. HR sẽ chốt lịch và báo lại.",
    availableFailed: "Không gửi được",
    emptyUpcomingTitle: "Chưa có lịch phỏng vấn",
    emptyUpcomingMessage: "Khi nhà tuyển dụng hẹn lịch, buổi phỏng vấn sẽ hiện ở đây để bạn xác nhận.",
    emptyPastTitle: "Chưa có buổi nào đã qua",
    emptyPastMessage: "Các buổi phỏng vấn đã diễn ra sẽ được lưu ở đây.",
    meetingFailed: "Không mở được liên kết phòng họp",
  },
  offers: {
    title: "Thư mời",
    subtitle: "Thư mời nhận việc từ nhà tuyển dụng",
    salary: "Mức lương",
    deadline: "Hạn phản hồi",
    respond: "Xem và phản hồi",
    view: "Xem chi tiết",
    emptyTitle: "Chưa có thư mời",
    emptyMessage: "Khi bạn vượt qua các vòng phỏng vấn, thư mời nhận việc sẽ hiện ở đây.",
  },
  offerDetail: {
    title: "Thư mời nhận việc",
    deadlineLeft: (d: string) => `Hạn phản hồi còn ${d}`,
    confirmTitle: "Xác nhận",
    agree: "Tôi đồng ý với các điều khoản trong thư mời",
    agreeRequired: "Đánh dấu đồng ý trước khi chấp nhận",
    acceptSign: "Chấp nhận",
    downloadPdf: "Tải PDF",
    pdfFailed: "Không tải được PDF thư mời",
    pdfWebUnsupported: "Tải PDF chỉ hỗ trợ trên ứng dụng điện thoại.",
    congrats: (name: string) => (name ? `Chúc mừng, ${name}!` : "Chúc mừng bạn!"),
    intro: (job: string) => `Bạn nhận được thư mời cho vị trí ${job}.`,
    timeLeft: "Thời hạn phản hồi còn lại",
    expired: "Đã quá hạn phản hồi",
    details: "Chi tiết đề nghị",
    salary: "Mức lương",
    perMonth: "/tháng",
    contract: "Loại hợp đồng",
    startDate: "Ngày bắt đầu",
    probation: "Thử việc",
    probationMonths: (m: number) => `${m} tháng`,
    allowance: "Phụ cấp",
    benefits: "Phúc lợi",
    note: "Lời nhắn từ nhà tuyển dụng",
    declinedReason: "Lý do từ chối",
    accept: "Nhận việc",
    decline: "Từ chối",
    acceptTitle: "Xác nhận nhận việc?",
    acceptMessage: "Nhà tuyển dụng sẽ nhận được phản hồi của bạn ngay. Bạn không đổi lại được sau khi xác nhận.",
    acceptConfirm: "Xác nhận nhận việc",
    accepted: "Bạn đã nhận việc. Nhà tuyển dụng sẽ liên hệ về ngày bắt đầu.",
    declineTitle: "Từ chối thư mời",
    declineMessage: "Cho nhà tuyển dụng biết lý do. Bạn không đổi lại được sau khi gửi.",
    reason: "Lý do",
    reasonRequired: "Chọn một lý do",
    declineNote: "Ghi chú thêm (không bắt buộc)",
    declineConfirm: "Gửi từ chối",
    declined: "Đã gửi phản hồi từ chối.",
    reasonsError: "Không tải được danh sách lý do.",
    failed: "Không gửi được phản hồi",
  },
  welcome: {
    title: (name: string) => (name ? `Chào mừng ${name}!` : "Chào mừng bạn!"),
    message: (job: string) => `Bạn đã nhận thư mời vị trí ${job}. Nhà tuyển dụng sẽ liên hệ về ngày bắt đầu và giấy tờ cần chuẩn bị.`,
    viewOffer: "Xem lại thư mời",
    home: "Về trang việc làm",
  },
  profile: {
    title: "Tôi",
    cvInUse: "Đang dùng",
    privacy: "Dữ liệu & quyền riêng tư",
    deleteTitle: "Xóa hồ sơ ứng viên",
    deleteMessage:
      "Hồ sơ, CV và thông tin cá nhân của bạn sẽ bị xóa khỏi hệ thống ngay, các đơn đang xét sẽ không được tiếp tục. Không thể hoàn tác.",
    deleteAgree: "Tôi hiểu và muốn xóa hồ sơ",
    deleteConfirm: "Xóa hồ sơ",
    deleted: "Đã gửi yêu cầu xóa hồ sơ.",
    deleteFailed: "Không xóa được hồ sơ",
    completion: (p: number) => `${p}% hoàn thiện`,
    cv: "CV ứng tuyển",
    noCv: "Chưa có CV",
    noCvHint: "Tải CV lên để có thể ứng tuyển. Nhận PDF, DOC, DOCX, tối đa 10 MB.",
    uploadCv: "Tải lên",
    replaceCv: "Thay",
    cvUploaded: "Đã cập nhật CV.",
    cvFailed: "Tải CV thất bại",
    cvTooLarge: "CV vượt quá 10 MB.",
    info: "Thông tin cá nhân",
    edit: "Sửa",
    phone: "Số điện thoại",
    dateOfBirth: "Ngày sinh",
    gender: "Giới tính",
    address: "Địa chỉ",
    currentPosition: "Vị trí hiện tại",
    education: "Học vấn",
    skills: "Kỹ năng",
    notSet: "Chưa cập nhật",
    offers: "Thư mời nhận việc",
    notifications: "Thông báo",
    signOut: "Đăng xuất",
    genders: { MALE: "Nam", FEMALE: "Nữ", OTHER: "Khác" },
    editTitle: "Sửa thông tin cá nhân",
    fullName: "Họ và tên",
    dobPlaceholder: "dd/mm/yyyy",
    dobInvalid: "Ngày sinh theo dạng dd/mm/yyyy",
    phoneInvalid: "Số điện thoại không hợp lệ",
    pickEducation: "Chọn trình độ học vấn",
    save: "Lưu",
    saved: "Đã lưu thông tin.",
    saveFailed: "Lưu thất bại",
  },
  notifications: {
    title: "Thông báo",
    readAll: "Đọc hết",
    unread: "Mới",
    earlier: "Trước đó",
    emptyTitle: "Chưa có thông báo",
    emptyMessage: "Khi đơn, lịch phỏng vấn hay thư mời của bạn có thay đổi, thông báo sẽ hiện ở đây.",
    open: "Thông báo",
  },
  errorState: {
    title: "Không tải được dữ liệu",
    fallback: "Kiểm tra kết nối mạng rồi thử lại.",
  },
  tabs: {
    candidate: {
      jobs: "Việc làm",
      applications: "Hồ sơ",
      interviews: "Lịch",
      notifications: "Thông báo",
      profile: "Tôi",
    },
    hm: {
      todo: "Cần duyệt",
      interviews: "Phỏng vấn",
    },
    hr: {
      home: "Tổng quan",
      requisitions: "Yêu cầu TD",
      applications: "Hồ sơ",
    },
  },
  placeholder: {
    session: "Phiên đăng nhập",
    email: "Email",
    role: "Vai trò",
    department: "Phòng ban",
    signOut: "Đăng xuất",
  },
  roles: {
    COMPANY_ADMIN: "Quản trị doanh nghiệp",
    RECRUITER: "Chuyên viên tuyển dụng",
    HIRING_MANAGER: "Quản lý tuyển dụng",
    CANDIDATE: "Ứng viên",
  },

  /** Nhãn trạng thái — chỉ đọc qua `src/lib/status.ts`, đừng lấy thẳng ở màn hình. */
  status: {
    stage: {
      APPLIED: "Ứng tuyển",
      CV_SCREENING: "Sàng lọc CV",
      HR_SCREENING: "Sàng lọc HR",
      TECHNICAL_INTERVIEW: "PV kỹ thuật",
      HR_INTERVIEW: "PV HR",
      FINAL_INTERVIEW: "PV vòng cuối",
      OFFER: "Đề nghị nhận việc",
      HIRED: "Đã tuyển dụng",
      REJECTED: "Từ chối",
      CUSTOM: "Vòng khác",
    },
    interview: {
      SCHEDULED: "Chờ HM xác nhận",
      HM_RESCHEDULE_PROPOSED: "HM đề xuất đổi giờ",
      HM_CONFIRMED: "Chờ ứng viên xác nhận",
      CANDIDATE_CONFIRMED: "Đã xác nhận",
      EVALUATION_PENDING: "Chờ đánh giá",
      COMPLETED: "Hoàn tất",
      NO_SHOW: "Vắng mặt",
      CANCELLED: "Đã hủy",
    },
    /** Ứng viên nhìn cùng một trạng thái theo góc của mình. */
    interviewForCandidate: {
      HM_CONFIRMED: "Chờ xác nhận",
      EVALUATION_PENDING: "Đã diễn ra",
      COMPLETED: "Đã diễn ra",
    },
    offer: {
      DRAFT: "Nháp",
      PENDING_APPROVAL: "Chờ duyệt",
      APPROVED: "Đã gửi ứng viên",
      REJECTED: "Không được duyệt",
      ACCEPTED: "Đã nhận việc",
      DECLINED: "Ứng viên từ chối",
    },
    offerForCandidate: {
      APPROVED: "Chờ phản hồi",
      DECLINED: "Đã từ chối",
    },
    requisition: {
      DRAFT: "Nháp",
      PENDING_APPROVAL: "Chờ duyệt",
      APPROVED: "Đã duyệt",
      REJECTED: "Bị từ chối",
      CHANGES_REQUESTED: "Cần chỉnh sửa",
    },
    posting: {
      DRAFT: "Nháp",
      EDITING: "Đang sửa",
      APPROVED: "Đã duyệt",
      OPEN: "Đang tuyển",
      PAUSED: "Tạm dừng",
      CLOSED: "Đã đóng",
    },
    unknown: "Không rõ",
  },
} as const;
